### ISSUE TITLE
后续建议加音频识别后的文本编辑功能

### ISSUE THREAD

**Issue by anzchy** [xiaolai/everyone-can-use-english#110]
enjoy.app音频转文本 识别率已经很高，不过偶尔还是有错误，建议后续增加文本手动编辑的功能。

**Comment by an-lee** [comment]
这个功能是有开发计划的。

**Comment by DeanLee2013** [comment]
https://app.notta.ai/ 可以参考这个STT

**Comment by an-lee** [comment]
在 #592 实现了

**Comment by an-lee** [comment]
Finished in [v0.2.4](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.2.4)
