### ISSUE TITLE
安装过程异常

### ISSUE THREAD

**Issue by arturiamu** [xiaolai/everyone-can-use-english#117]
在安装ffmpeg阶段，安装完ffmpeg后需要点击“上一步”，再点击“下一步”回到安装ffmpeg阶段，才会提示ffmpeg安装完成

**Comment by an-lee** [comment]
在 #116 中优化了流程，等下一个版本再试一下看。

**Comment by an-lee** [comment]
fixed in v0.1.0.alpha-4
