### ISSUE TITLE
为什么必须做登录校验，是否可以提供个游客的功能。

### ISSUE THREAD

**Issue by wenkikro** [xiaolai/everyone-can-use-english#122]
运行程序后，弹出操作框，提示必须使用Mixin Messenger 扫码登录。如果没有相关的应用，可以提供一个类似游客访问的功能吗？

**Comment by yuan6785** [comment]
是啊，同样的困惑

**Comment by an-lee** [comment]
用户系统对于很多核心功能是必须的，只是目前暂时只支持 Mixin 登录。后续会增加更多验证方式。
游客功能暂时不考虑。

**Comment by cikiChe** [comment]
兄弟们，mixin在哪里下载，怎么下完之后要升级版本，不升级不然注册，死循环了

**Comment by cikiChe** [comment]
> 兄弟们，mixin在哪里下载，怎么下完之后要升级版本，不升级不然注册，死循环了

搞懂了，我的网络无法访问mixin网站，然后换成了移动网络，终于可以访问了。然后又发现要通过google play安装，好吧劝退华为机

**Comment by OPEN-F** [comment]
华为手机使用谷歌，可以使用Gspace环境，利用虚拟机使用谷歌环境

**Comment by tudan110** [comment]
Mixin Messenger 是什么软件，怎么说是加密货币？

**Comment by cikiChe** [comment]
我在来反馈下，mixin 用16号段无法注册

**Comment by triangle959** [comment]
everyone-can-use-english-after-they-use-mixin
给自个的应用拉人头了，真是好营销啊

**Comment by an-lee** [comment]
增加了 Github 登录
