### ISSUE TITLE
建议：添加单次播放，切换上一句，下一句。

### ISSUE THREAD

**Issue by vwumumu** [xiaolai/everyone-can-use-english#124]
目前是单据循环，建议添加只播放一次，以及切换上一句，下一句。

对应的场景是反复练习完一句，并且可以保持此模式切换上、下一句。

**Comment by an-lee** [comment]
意思是，整句播放一次，然后自动暂停是吗？

那就是三种播放模式切换：

1. 连续播放
2. 单句循环
3. 单句播放

**Comment by vwumumu** [comment]
> 意思是，整句播放一次，然后自动暂停是吗？
> 
> 那就是三种播放模式切换：
> 
> 1. 连续播放
> 2. 单句循环
> 3. 单句播放

是的
