### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lerogo** [xiaolai/everyone-can-use-english#126]
```bash
# This file contains the result of Yarn building a package (electron@npm:28.1.3)
# Script name: postinstall

RequestError: connect ETIMEDOUT 20.205.243.166:443
    at ClientRequest.<anonymous> (./everyone-can-use-english-main/enjoy/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (./everyone-can-use-english-main/enjoy/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```

**Comment by mdddj** [comment]
同样的错误

**Comment by xiaochen0517** [comment]
Check the network environment, using proxy tools may help alleviate the issue.

**Comment by mdddj** [comment]
开全局也没用,有没有可能20.205.243.166的证书过期导致的大佬

**Comment by xiaochen0517** [comment]
> 开全局也没用,有没有可能20.205.243.166的证书过期导致的大佬

我觉得有可能是你的dns有问题，你可以排查一下。

**Comment by lfxiui** [comment]
同样的错误，用了镜像，用了代理都不管用

**Comment by xiaochen0517** [comment]
> 同样的错误，用了镜像，用了代理都不管用

使用的是脚本安装方式吗？

**Comment by lerogo** [comment]
> > 同样的错误，用了镜像，用了代理都不管用
> 
> 安装方式是什么？

你把你的缓存清掉，然后再下载zip解压，然后yarn重新安装一下试试，安装不了，yarn npm都不行。

```bash
# mac os: 14.2.1
# dns: 8.8.8.8、8.8.4.4、2001:4860:4860::8888和2001:4860:4860::8844

% yarn --version
4.0.2
% node --version
v21.5.0
% npm --version
8.3.1
```

**Comment by xiaochen0517** [comment]
下面这是我的安装运行的结果截图：

![image](https://github.com/xiaolai/everyone-can-use-english/assets/30149408/8c8428d3-e56c-4dcd-86af-876dd8229cda)
![image](https://github.com/xiaolai/everyone-can-use-english/assets/30149408/18076129-67a4-4406-9def-924b47238f4a)

一般来说此问题来源于网络问题，开启代理的 `tun` 模式应该可以解决此问题。

可以尝试 `clone` 项目，`checkout` 到 `tags/v0.1.0-alpha.3` 尝试 `yarn install`，如果还是同样的问题那就可以确定是网络问题。

通常代理工具只会设置系统代理为本地的代理入口，但是一些终端及软件默认不会使用配置的代理入口，因此可能会引发此问题。可以尝试配置 `npm` 或 `yarn` 的代理地址，或者开启代理工具的 `tun` 模式。

**Comment by lfxiui** [comment]
macos，yarn 4.0.2
通过设置electron镜像解决了
`export ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"`
ps：网上的设置electron镜像方法👇在yarn 4.0.2不管用
`yarn config set electron_mirror https://npmmirror.com/mirrors/electron/`

**Comment by mdddj** [comment]
> macos，yarn 4.0.2 通过设置electron镜像解决了 `export ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"` ps：网上的设置electron镜像方法👇在yarn 4.0.2不管用 `yarn config set electron_mirror https://npmmirror.com/mirrors/electron/`

这个有用,赞

**Comment by lerogo** [comment]
> 下面这是我的安装运行的结果截图：
> 
> ![image](https://private-user-images.githubusercontent.com/30149408/297286540-8c8428d3-e56c-4dcd-86af-876dd8229cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzYwMzUsIm5iZiI6MTcwNTQ3NTczNSwicGF0aCI6Ii8zMDE0OTQwOC8yOTcyODY1NDAtOGM4NDI4ZDMtZTU2Yy00ZGNkLTg2YWYtODc2ZGQ4MjI5Y2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3MTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlM2MyMTI0MDVjYTY0YWZmNTcyNzZkNzA3MmJhZGZiZjU0OGIwYWM4YmE1OGE0MTU3MTFlOWE0NmE0MTEwZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BPcjq5idMQg4aCTzXPjOJf7jm3dK8STetsCBcgf0r7Q) ![image](https://private-user-images.githubusercontent.com/30149408/297286911-18076129-67a4-4406-9def-924b47238f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzYwMzUsIm5iZiI6MTcwNTQ3NTczNSwicGF0aCI6Ii8zMDE0OTQwOC8yOTcyODY5MTEtMTgwNzYxMjktNjdhNC00NDA2LTlkZWYtOTI0YjQ3MjM4ZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3MTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNzVhNGM1ODA4NWE1YWU3Mzk4ZjM2Y2FiYTdhNGJhYmE0YWMxZTg2MDA5M2NhNDJhNjQyMDUxNjYyYjg1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0tIaD2EBZ9_EwfdOAm0LA8tYgPRTsFS-VL7IZr7WXqI)
> 
> 一般来说此问题来源于网络问题，开启代理的 `tun` 模式应该可以解决此问题。
> 
> 可以尝试 `clone` 项目，`checkout` 到 `tags/v0.1.0-alpha.3` 尝试 `yarn install`，如果还是同样的问题那就可以确定是网络问题。
> 
> 通常代理工具只会设置系统代理为本地的代理入口，但是一些终端及软件默认不会使用配置的代理入口，因此可能会引发此问题。可以尝试配置 `npm` 或 `yarn` 的代理地址，或者开启代理工具的 `tun` 模式。

这样应该是无用的，因为我们一般会使用“export https_proxy=http://127.0.0.1:1080 http_proxy=http://127.0.0.1:1080 all_proxy=socks5://127.0.0.1:1080”

**Comment by lerogo** [comment]
> macos，yarn 4.0.2 通过设置electron镜像解决了 `export ELECTRON_MIRROR="https://npmmirror.com/mirrors/electron/"` ps：网上的设置electron镜像方法👇在yarn 4.0.2不管用 `yarn config set electron_mirror https://npmmirror.com/mirrors/electron/`

这个有用！

**Comment by xiaochen0517** [comment]
> > 下面这是我的安装运行的结果截图：
> > ![image](https://private-user-images.githubusercontent.com/30149408/297286540-8c8428d3-e56c-4dcd-86af-876dd8229cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzYwMzUsIm5iZiI6MTcwNTQ3NTczNSwicGF0aCI6Ii8zMDE0OTQwOC8yOTcyODY1NDAtOGM4NDI4ZDMtZTU2Yy00ZGNkLTg2YWYtODc2ZGQ4MjI5Y2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3MTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlM2MyMTI0MDVjYTY0YWZmNTcyNzZkNzA3MmJhZGZiZjU0OGIwYWM4YmE1OGE0MTU3MTFlOWE0NmE0MTEwZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BPcjq5idMQg4aCTzXPjOJf7jm3dK8STetsCBcgf0r7Q) ![image](https://private-user-images.githubusercontent.com/30149408/297286911-18076129-67a4-4406-9def-924b47238f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzYwMzUsIm5iZiI6MTcwNTQ3NTczNSwicGF0aCI6Ii8zMDE0OTQwOC8yOTcyODY5MTEtMTgwNzYxMjktNjdhNC00NDA2LTlkZWYtOTI0YjQ3MjM4ZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA3MTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNzVhNGM1ODA4NWE1YWU3Mzk4ZjM2Y2FiYTdhNGJhYmE0YWMxZTg2MDA5M2NhNDJhNjQyMDUxNjYyYjg1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0tIaD2EBZ9_EwfdOAm0LA8tYgPRTsFS-VL7IZr7WXqI)
> > 一般来说此问题来源于网络问题，开启代理的 `tun` 模式应该可以解决此问题。
> > 可以尝试 `clone` 项目，`checkout` 到 `tags/v0.1.0-alpha.3` 尝试 `yarn install`，如果还是同样的问题那就可以确定是网络问题。
> > 通常代理工具只会设置系统代理为本地的代理入口，但是一些终端及软件默认不会使用配置的代理入口，因此可能会引发此问题。可以尝试配置 `npm` 或 `yarn` 的代理地址，或者开启代理工具的 `tun` 模式。
> 
> 这样应该是无用的，因为我们一般会使用“export https_proxy=http://127.0.0.1:1080 http_proxy=http://127.0.0.1:1080 all_proxy=socks5://127.0.0.1:1080”

你说的这个是设置系统代理，但是有很多软件和工具是不会使用本地代理的，还需要额外设置软件的代理。

或者直接打开 `tun` 模式，所有的流量都会经过本地代理服务。
