### ISSUE TITLE
yarn start enjoy with error: ERR_SOCKET_NOT_CONNECTED

### ISSUE THREAD

**Issue by jackbaron** [xiaolai/everyone-can-use-english#141]
![Screenshot from 2024-01-17 11-40-22](https://github.com/xiaolai/everyone-can-use-english/assets/25658880/4ea57024-7006-42e2-80aa-008d98d8664d)

I got the error when  I run command `yarn start:enjoy`. How to fix it?

**Comment by birdmanmandbir** [comment]
是不是install就失败了，麻烦贴下yarn install的截图

**Comment by jackbaron** [comment]
![image](https://github.com/xiaolai/everyone-can-use-english/assets/25658880/760c285b-34c4-4c5e-abdb-e372d44bcef2)
@birdmanmandbir This is my result when I run the yarn install command

**Comment by birdmanmandbir** [comment]
The ﻿yarn install log appears to be fine. If you only intend to use this project, I recommend installing the executable from the release.
