### ISSUE TITLE
点击音频的分享按钮，服务器报错code:500

### ISSUE THREAD

**Issue by sophychow** [xiaolai/everyone-can-use-english#146]
点击分享按钮后：
![image](https://github.com/xiaolai/everyone-can-use-english/assets/11385675/ce370d63-6744-4ca4-a2ef-2317c969ab2f)

接口：
![image](https://github.com/xiaolai/everyone-can-use-english/assets/11385675/70795e80-dec8-44f0-8a55-892827ed1be4)
入参：
![image](https://github.com/xiaolai/everyone-can-use-english/assets/11385675/434b3d18-04d0-4a35-99c0-703380eeec1d)
响应：
![image](https://github.com/xiaolai/everyone-can-use-english/assets/11385675/fceed5ba-3fe1-4543-994b-3ddc075f7687)

**Comment by an-lee** [comment]
it's a server bug. it should be fixed now
