### ISSUE TITLE
mac无法录音

### ISSUE THREAD

**Issue by garlicman-man** [xiaolai/everyone-can-use-english#149]
看起来并没有请求麦克风权限，我在麦克风权限列表里也没这个Electron

**Comment by rrobert551** [comment]
You can set it on your device. to open, close or use Especially on browser programs.

[movie 2024](https://moviehd2024.com/)

**Comment by garlicman-man** [comment]
> You can set it on your device. to open, close or use Especially on browser programs.
> 
> [movie 2024](https://moviehd2024.com/)

这是无关广告 不要点开

**Comment by lgqbee** [comment]
你的问题解决了吗？我当时也是Enjoy.app调用不了麦克风，麦克风权限那没有该app可以选。我把Enjoy.app，放进“系统设置”-“隐私与安全性”-“App管理里”，就能用麦克风了。可能Enjoy.app是不是在app store里下的，有限制。
![截屏2024-01-21 07 57 54](https://github.com/xiaolai/everyone-can-use-english/assets/57405578/f8a43c67-6a1d-462c-97c8-d4269e7240e7)

**Comment by garlicman-man** [comment]
> 你的问题解决了吗？我当时也是Enjoy.app调用不了麦克风，麦克风权限那没有该app可以选。我把Enjoy.app，放进“系统设置”-“隐私与安全性”-“App管理里”，就能用麦克风了。可能Enjoy.app是不是在app store里下的，有限制。 ![截屏2024-01-21 07 57 54](https://private-user-images.githubusercontent.com/57405578/298313383-f8a43c67-6a1d-462c-97c8-d4269e7240e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTU2NDksIm5iZiI6MTcwNTc5NTM0OSwicGF0aCI6Ii81NzQwNTU3OC8yOTgzMTMzODMtZjhhNDNjNjctNmExZC00NjJjLTk3YzgtZDQyNjllNzI0MGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAwMDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTI5MTg2OWMwZTFkZTAxYTRlNjc3MGZlOTJhNTU0NDA4ZTAwODkzMWY2ZjdjOWRmNzEyZjVkYzM1NTc0YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVsS5OaHW0R9hm5ISfKOnXEk3z4DLtFHQuNuIM6nW24)

新版本代码修复了 会请求麦克风(.4 version)
