### ISSUE TITLE
 Enjoy 第4步出现问题进行不下去了

### ISSUE THREAD

**Issue by dongdong0221** [xiaolai/everyone-can-use-english#154]
![WechatIMG269](https://github.com/xiaolai/everyone-can-use-english/assets/51995026/40bb92d8-0a17-4afb-8cfd-f27cc8d535b0)
安装完 FFmpeg 后 点击查找，出现未检测到 FFmpeg 命令 提示。
有知道怎么解决吗？

**Comment by solepole** [comment]
需要管理员权限，在Teriminal下执行
sudo open /Applications/Enjoy.app

**Comment by an-lee** [comment]
should be fixed now.

**Comment by izhanyouxin** [comment]
我也是同样的问题，还没解决掉
 at bogon in ~
$ which ffmpeg
/usr/local/bin/ffmpeg
(base)
enjoy查找不到ffmpeg

**Comment by izhanyouxin** [comment]
$ sudo open /Applications/Enjoy.app
Password:
The file /Applications/Enjoy.app does not exist.
(base)

**Comment by izhanyouxin** [comment]
尝试了一下https://juejin.cn/post/6974945377313112071，再安装最新的enjoy，已经可以了，我把enjoy放路径：/Applications/Enjoy.app
