### ISSUE TITLE
找不到FFmpeg

### ISSUE THREAD

**Issue by miztermango** [xiaolai/everyone-can-use-english#157]
试过文件夹、试了全局，最终都提示找不到FFmpeg。
<img width="1591" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/49216577/4fd9282c-492f-4cb2-9294-1328b5fbd7c4">

**Comment by an-lee** [comment]
`which ffmpeg`  看看？可能是旧版本的 Homebrew 安装目录没有在截图里的检索范围里。

临时解决办法是创建一个软链接到上面任意目录里，大概是一下这样的命令

```
ln -s /usr/local/bin/ffmpeg ~/Documents/EnjoyLibrary/ffmpeg/ffmpeg
ln -s /usr/local/bin/ffprobe ~/Documents/EnjoyLibrary/ffmpeg/ffprobe
```

下一个版本会增加检索目录，解决这个问题

**Comment by miztermango** [comment]
我把ffmpeg cd到application下和enjoy一起都在这个application里了，我等您那边的版本更新吧，谢谢啦！
<img width="844" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/49216577/be04ec7a-17f4-4d4d-b5a6-15afe04517e6">

**Comment by miztermango** [comment]
<img width="984" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/49216577/e0c75f0a-a7f0-4f0a-9618-2448044fbf37">
把 ffprobe放进ffmpeg的文件夹，然后scan，可以了，我又行了，哈哈哈！

**Comment by an-lee** [comment]
should be fixed now.
