### ISSUE TITLE
运行时提示损坏

### ISSUE THREAD

**Issue by Warren-swr** [xiaolai/everyone-can-use-english#162]
Mac M1 版本，运行 Enjoy-darwin-arm64-0.1.0-alpha.3 提示损坏
<img width="372" alt="截屏2024-01-19 14 19 48" src="https://github.com/xiaolai/everyone-can-use-english/assets/77431161/d23ae498-2922-42ed-99c5-5d44fafdf07d">

**Comment by an-lee** [comment]
因为 Enjoy 目前还有签名，所以会被 Apple 的安全机制拦截。如果需要使用，可以自行授权，详细可以参考 [这里](https://github.com/xiaolai/everyone-can-use-english/blob/main/find-compatible-software-version.md)
