### ISSUE TITLE
cannot read properties of undefined(reading"text")

### ISSUE THREAD

**Issue by zhangzhiyong2025** [xiaolai/everyone-can-use-english#163]
出现“cannot read properties of undefined(reading"text")" 的错误（如图），是那个环节出问题了？我应该怎么做？
![56c039f753ba3b6e02aaaa8aa845923](https://github.com/xiaolai/everyone-can-use-english/assets/103319151/66ceae87-f83f-4b3a-8990-665ea97d06a8)

**Comment by an-lee** [comment]
用的是哪个版本？ v0.1.0.alpha-3 吗？

**Comment by an-lee** [comment]
should be fixed in v0.1.0.alpha-4

**Comment by zhangzhiyong2025** [comment]
更新到了v0.1.0.alpha-4，还是一样的提示。

**Comment by zhangzhiyong2025** [comment]
是不是我open ai 买的有问题，我买的是中转的。

**Comment by zhangzhiyong2025** [comment]
接口地址就按商家提供的地址填的。

**Comment by zhangzhiyong2025** [comment]
我买的open ai 没有问题，在其他地放可以正常使用

**Comment by long-bin** [comment]
enjoy版本：v0.1.0-alpha.6

系统：win 11 专业版 23H2 版本：22631.3085

报跟上面一样的错

<img width="1190" alt="enjoy_uw7Mb2Lb4V" src="https://github.com/xiaolai/everyone-can-use-english/assets/34160928/d085cffc-a8fb-4e46-ae6b-ff77954e4171">

**Comment by zhangzhiyong2025** [comment]
搞定了，安装了版本9，接口地址后面加了  /v1
