### ISSUE TITLE
OpenAI的ChatGPT用户，不知道如何获取request endpoint和TTS base URL, 如图。

### ISSUE THREAD

**Issue by miztermango** [xiaolai/everyone-can-use-english#166]
已经填写了api Key，但这两个链接填写的如图，怎么也不能用，返回的是connection error. 
<img width="596" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/49216577/17d37e4f-b860-4b94-a43b-eb3524256641">

**Comment by an-lee** [comment]
如果自己没有接口，留空就行。connect error 就是网络问题，访问不了 openAI 。可以自行解决网络问题，或者再等等后续的其他方案。
