### ISSUE TITLE
Cannot login Mixin

### ISSUE THREAD

**Issue by alexyang-sea** [xiaolai/everyone-can-use-english#170]
我直接下的windows的那个.exe文件安装的，但是安装时就提示要下载一个mi什么的客户端，但是点了下载就弹出错误。
![1](https://github.com/xiaolai/everyone-can-use-english/assets/137014157/5853c7e3-502c-47ad-935c-a742d5cfbe98)
![2](https://github.com/xiaolai/everyone-can-use-english/assets/137014157/2583298e-b87c-4ba2-96b6-356d0a9d042d)

**Comment by an-lee** [comment]
目前还只支持 Mixin 登录，如果不是 Mixin 用户，暂时无法使用。再等等

**Comment by an-lee** [comment]
Enjoy 新版已经支持更多登录方式，非 Mixin 帐号可以选用 Github 登录
