### ISSUE TITLE
跟读后语音条没有声音显示

### ISSUE THREAD

**Issue by dongruixue** [xiaolai/everyone-can-use-english#171]
我是 intel 架构的 Mac，点击下载了 “darwin-x64” 字样的 Enjoy 程序。翻译页可以正常使用，但跟读时，提示“末找到音频”，点麦克风跟读完成后没有声音。

<img width="1712" alt="截屏2024-01-20 08 10 44" src="https://github.com/xiaolai/everyone-can-use-english/assets/22710773/23a3aef1-9bba-4704-ae2c-92339917c866">
<img width="827" alt="截屏2024-01-20 08 10 34" src="https://github.com/xiaolai/everyone-can-use-english/assets/22710773/0c6f8d80-dc1c-48e1-baa9-41f940aa9458">
<img width="1222" alt="截屏2024-01-20 08 09 15" src="https://github.com/xiaolai/everyone-can-use-english/assets/22710773/99b52628-7000-414d-ba52-73fbdab32948">
<img width="392" alt="截屏2024-01-20 08 08 49" src="https://github.com/xiaolai/everyone-can-use-english/assets/22710773/54530ba9-0df8-4fdd-9c8a-1eaa147b5592">
<img width="1712" alt="截屏2024-01-20 08 20 19" src="https://github.com/xiaolai/everyone-ca
<img width="1712" alt="截屏2024-01-20 08 23 27" src="https://github.com/xiaolai/everyone-can-use-english/assets/22710773/3f6f11b2-2c71-4b5b-9b52-3d64e16aa4b2">
n-use-english/assets/22710773/eac8bdee-9deb-4047-ae0d-65e1d4c3672f">
<img width="1712" alt="截屏2024-01-20 08 23 27" src="https://github.com/xiaolai/everyone-can-use-english/assets/22710773/5145b65f-d173-4551-869d-18b39f65747a">
<img width="1712" alt="截屏2024-01-20 08 20 19" src="https://github.com/xiaolai/everyone-can-use-english/assets/22710773/b3198f33-f5aa-4cf5-8143-e25b1e7b9e00">

**Comment by an-lee** [comment]
duplicated #149

**Comment by dongruixue** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by an-lee** [comment]
should be fixed in [v0.1.0-alpha.5](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.5)
