### ISSUE TITLE
STT 模型只针对 macOS 12 么？

### ISSUE THREAD

**Issue by pierrelzw** [xiaolai/everyone-can-use-english#175]
检查语音转文字模型时，出现以下错误
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/595873c5-23f8-4424-a35c-ccdc94e7591b)

我的macOS 还是 11.7 。因为是 2014 年的 mac，所以暂时没法升级到 macOS 12 及以上
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/031c8b92-56e8-4a43-865c-6b619883edf3)

**Comment by an-lee** [comment]
目前是的。正在搞替代方案。

**Comment by an-lee** [comment]
ref: #177

**Comment by pierrelzw** [comment]
> 目前是的。正在搞替代方案。

嗯嗯，感谢。因为是 2015 年的 mac，所以暂时没法升级到 macOS 12 及以上。
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/d1b66697-8bb0-4fc2-a809-63f22885abc3)

**Comment by yanyinn** [comment]
我也一样，早上还在想要不要按照[这个教程](https://sysin.org/blog/install-macos-12-on-unsupported-mac/)，强制升级到macOS 12，后来想想算了，太麻烦了，反正这个任务的核心是跟读，朗读，生学硬练就行。

**Comment by an-lee** [comment]
可以试试最新版 [v0.1.0-alpha.7](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.7) ，可以选用 Azure AI 作为 语音转文字 服务，whipser 变成可选项。
