### ISSUE TITLE
页面的一点小bug :  support dark theme

### ISSUE THREAD

**Issue by yanyinn** [xiaolai/everyone-can-use-english#179]
<img width="1392" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/109458303/300e5acc-2f46-4f10-b4f3-0bed307728c5">

1.不知道是不是夜间模式导致的，晚上格子全变黑了，看上去非常突兀。下面是夜间模式的github格子，这样就好看些
<img width="768" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/109458303/2ce28ca2-a176-4385-89cd-de6e99266a38">

2.月份的英文重叠了，或许也可以学下github，用缩写

**Comment by an-lee** [comment]
夜间模式还没支持

**Comment by an-lee** [comment]
v0.2.3 已经支持。
