### ISSUE TITLE
App功能：跟读训练-单词翻译功能问题

### ISSUE THREAD

**Issue by lgqbee** [xiaolai/everyone-can-use-english#180]
macOS 13.6.3，已试用一周App，“跟读训练-单词翻译”功能前几天是能用的，直到两三天前，突然无法使用。试过切换内外网络了。仍未解决问题。

![截屏2024-01-21 08 04 30](https://github.com/xiaolai/everyone-can-use-english/assets/57405578/82665f56-289e-4c19-95f8-8177c71ffb09)

**Comment by an-lee** [comment]
请下载最新的 [alpha.4 版本](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.4)

**Comment by lgqbee** [comment]
好的，收到。

**Comment by lgqbee** [comment]
我已更新版本，但问题仍然存在，我补充一下其他细节，用的open api 中转 key，已按客服教程配置，通过这种key直到2、3天前，都是可以正常使用翻译功能的。现在错误提示如下。
![image](https://github.com/xiaolai/everyone-can-use-english/assets/57405578/9e8f2cd7-39b0-4a8e-be90-b3289f6f7585)

**Comment by lgqbee** [comment]
![image](https://github.com/xiaolai/everyone-can-use-english/assets/57405578/c4990076-d1af-434f-bf5e-45574e45e070)

**Comment by an-lee** [comment]
> 我已更新版本，但问题仍然存在，我补充一下其他细节，用的open api 中转 key，已按客服教程配置，通过这种key直到2、3天前，都是可以正常使用翻译功能的。现在错误提示如下。 ![image](https://private-user-images.githubusercontent.com/57405578/298375177-9e8f2cd7-39b0-4a8e-be90-b3289f6f7585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4Mzc3MDAsIm5iZiI6MTcwNTgzNzQwMCwicGF0aCI6Ii81NzQwNTU3OC8yOTgzNzUxNzctOWU4ZjJjZDctMzliMC00YThlLWJlOTAtYjMyODlmNmY3NTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDExNDMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYmM3ZTAzZTM3N2VlYzlkYTg5YWEyODY1YTVhN2NmMGFhNDBmZjYyNTRlOGFiOTgxY2NiODNhNDdmODM5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hY7hn4h1E4ZJgYdGCpZadlc9Sf3rV3LSFbDG06Bsmw8)

在 软件设置 ->  基本设置 里设一下 OpenAI 的 接口地址，查词典这些功能是按照这个配置走

**Comment by an-lee** [comment]
#178 已经修了，等新版。

**Comment by lgqbee** [comment]
好的，辛苦了。

**Comment by an-lee** [comment]
should be fixed in [v0.1.0-alpha.5](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.5)
