### ISSUE TITLE
Is this just for Chinese 

### ISSUE THREAD

**Issue by crorodriguezro** [xiaolai/everyone-can-use-english#181]
Hi, I-m a spanish speaker. is it posible for me to use this repo without knowing any chinese?

**Comment by an-lee** [comment]
Enjoy is designed to assist anyone in learning any language. As you may have noticed, the software is currently in its early stages of development, so it might be a bit cumbersome to use. However, I encourage you to give it a try and share your feedback if you encounter any issues.

**Comment by UdayRajVadeghar** [comment]
pretty sure
