### ISSUE TITLE
请添加一下 Mac Intel 机器下的 ffmpeg 安装路径

### ISSUE THREAD

**Issue by Aresona** [xiaolai/everyone-can-use-english#184]
Mac Intel 机器下通过 Homebrew 安装的 ffmpeg 执行软件目录为 /usr/local/bin, 需要添加一个软件检测目录，目前好像只支持 Mac M1,M2,M3 的路径 /opt/homebrew/bin 目录。

**Comment by an-lee** [comment]
v0.1.0.alpha-4 已经添加 https://github.com/xiaolai/everyone-can-use-english/blob/a6548e0f44d448dde2f2e248b97ffd5a014b7e0d/enjoy/src/main/ffmpeg.ts#L444
