### ISSUE TITLE
运行一段时间后会报错 "A JavaScript error occurred in the browser process"

### ISSUE THREAD

**Issue by Jieqian-Chen** [xiaolai/everyone-can-use-english#190]
A JavaScript error occurred in the browser process
TypeError: Object has been destroyed at Hf.init (/Applications/Enjoy.app/
Contents/Resources/app/.vite/build/main-b8f72f47.js:380:1634) at App. <anonymous>(/Applications/ Enjoy.app/Contents/Resources/app/.vite/build/main-b8f72f47.js: 380:6403) at App.emit (node: events:517: 28)

**Comment by an-lee** [comment]
Thank you for your feedback. To assist you better, could you please specify your operating system, Enjoy version, and any other relevant details? Is the issue tied to a pop-up error? It would be very helpful if you could provide a screenshot.

**Comment by 542809** [comment]
我也遇到了同样的问题，需要重新安装程序才可以解决。只要退出程序后再进入就会报这个错误
![WechatIMG249](https://github.com/xiaolai/everyone-can-use-english/assets/57673231/dca33de3-6da0-4cd5-b629-f6ef8645f230)
我重新安装最新版本后，还遇到了录音界面闪现“cannot properties of undefined "字符条
![Uploading WechatIMG250.jpg…]()

**Comment by Jieqian-Chen** [comment]
> Thank you for your feedback. To assist you better, could you please specify your operating system, Enjoy version, and any other relevant details? Is the issue tied to a pop-up error? It would be very helpful if you could provide a screenshot.

<img width="260" alt="iShot_2024-01-30_17 25 05" src="https://github.com/xiaolai/everyone-can-use-english/assets/62493777/a4302c98-ac2b-487e-9e6d-3bb8c02801ac">
<img width="280" alt="iShot_2024-01-30_17 25 50" src="https://github.com/xiaolai/everyone-can-use-english/assets/62493777/9ab41a2f-3f06-485f-ae2e-c8266f78b36b">
重新安装了最新版本还是会出现。
目前判断应该是后台挂起的时候出现这个报错。
