### ISSUE TITLE
使用v0.1.0-alpha.5发现的Bug

### ISSUE THREAD

**Issue by cosyfish** [xiaolai/everyone-can-use-english#196]
macos:12.6.1
[v0.1.0-alpha.5](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.5)

碰到的bug：
1这里无法选择modle
<img width="1438" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/24654181/9f3a06d0-9960-464b-bb20-463f065d3b33">

2.到这个界面后，错误提示不停地跳出来。
<img width="1277" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/24654181/7ecc18e3-cfae-4264-a77e-6955fcf7052a">

3.关闭窗口后，再次点击软件打开。出现如下错误提示
<img width="269" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/24654181/475c3278-6d2e-4546-a23c-337f6f1adce6">

**Comment by an-lee** [comment]
在 #197 修复了。

新用户会触发这个 bug，临时解决办法是

1. 软件设置 -> 资源库路径 -> 打开
2. 在打开的文件夹下，新建一个文件夹 `whisper`，再进入 `whisper` 文件夹下，再建一个 `models` 文件夹
3. 关闭 软件设置，重新打开 软件设置，语音转文本 AI 模型 -> 修改，就可以正常下载模型了

**Comment by cosyfish** [comment]
> 在 #197 修复了。
> 
> 新用户会触发这个 bug，临时解决办法是
> 
> 1. 软件设置 -> 资源库路径 -> 打开
> 2. 在打开的文件夹下，新建一个文件夹 `whisper`，再进入 `whisper` 文件夹下，再建一个 `models` 文件夹
> 3. 关闭 软件设置，重新打开 软件设置，语音转文本 AI 模型 -> 修改，就可以正常下载模型了

谢谢你的回复，我按照你的方法的确在进入的界面可以看到模型了，但是一直下载不下来了。
备注：我的网络是通畅的。

**Comment by cosyfish** [comment]
点击下载之后很长时间就停留在这个地方：
<img width="475" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/24654181/599f855c-bddd-447f-ac0e-b61e0c99a366">

**Comment by an-lee** [comment]
[base](https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin) 试试直接下载？应该就是网络问题。

不行的话，先下这个 [tiny](https://enjoy-storage.baizhiheizi.com/ggml-tiny.en.bin) ，放到 models 文件夹里就行

**Comment by cosyfish** [comment]
> [base](https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin) 试试直接下载？应该就是网络问题。
> 
> 不行的话，先下这个 [tiny](https://enjoy-storage.baizhiheizi.com/ggml-tiny.en.bin) ，放到 models 文件夹里就行



谢谢你的回复。我搞定了AI模型，但是进入录音的界面，这个错误就不停地跳出来。
<img width="1425" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/24654181/45917058-1739-4f76-9c07-68d57f20f035">

**Comment by cosyfish** [comment]
我在 软件设置->语音转AI模型->检查，正常之后就可以使用了。
