### ISSUE TITLE
STT AI model assets download always in progress.

### ISSUE THREAD

**Issue by sontjer** [xiaolai/everyone-can-use-english#198]
![Screenshot from 2024-01-23 22-00-54](https://github.com/xiaolai/everyone-can-use-english/assets/43029800/94dc1bc4-3f10-4a9d-815b-277b1f0de55d)
 On Debian12 gnome, app ver. Alpha 5, even the stt ai model assets download progress is over, it just stuck there, and the check result always is whisper not working. What I can confirm is that I directory is there, safe and sound, and the connection is smooth and unbothered.

**Comment by sontjer** [comment]
I manually downloaded the assets from https://ggml.ggerganov.com, however, didnt seem to work properly by placing in EnjoyLibrary/whisper/ directory.

**Comment by an-lee** [comment]
> I manually downloaded the assets from https://ggml.ggerganov.com, however, didnt seem to work properly by placing it in EnjoyLibrary/whisper/ directory.

it should be in `EnjoyLibrary/whisper/models`

**Comment by an-lee** [comment]
and the filename must match.

Enjoy is trying to download from here: https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin

**Comment by sontjer** [comment]
Thank you for your response,  will try it out tomorrow.

**Comment by sontjer** [comment]
![Screenshot from 2024-01-24 08-12-45](https://github.com/xiaolai/everyone-can-use-english/assets/43029800/0770949f-8ef6-4727-b84e-003a186b8c7b)
Even it marks a tick, meaning I downloaded the assets, it just cannot pass the check. 
![Screenshot from 2024-01-24 08-13-16](https://github.com/xiaolai/everyone-can-use-english/assets/43029800/3a13207f-8f5c-4d46-b9d8-8c0aa1eba277)

**Comment by an-lee** [comment]
> ![Screenshot from 2024-01-24 08-12-45](https://private-user-images.githubusercontent.com/43029800/299137128-0770949f-8ef6-4727-b84e-003a186b8c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTk4MTEsIm5iZiI6MTcwNjA1OTUxMSwicGF0aCI6Ii80MzAyOTgwMC8yOTkxMzcxMjgtMDc3MDk0OWYtOGVmNi00NzI3LWI4NGUtMDAzYTE4NmI4YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYWY2MTYzMTg5NGIzNzAzM2Q4NTVkZmU4M2YxMjMyMTY3ZDNmNWQ0YWQ1OWQ0NmQ5NGE2YjQzOGMyNmU2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlTimXXoAsMoyb761C4iOES4ZkMdhYjbqnOMUUquf3Y) Even it marks a tick, meaning I downloaded the assets, it just cannot pass the check. ![Screenshot from 2024-01-24 08-13-16](https://private-user-images.githubusercontent.com/43029800/299137217-3a13207f-8f5c-4d46-b9d8-8c0aa1eba277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTk4MTEsIm5iZiI6MTcwNjA1OTUxMSwicGF0aCI6Ii80MzAyOTgwMC8yOTkxMzcyMTctM2ExMzIwN2YtOGY1Yy00ZDQ2LWI5ZDgtOGMwYWExZWJhMjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTE1NjA0YWY5YzAzMjY1NGZlYzY3NTY3N2NlODNlNDBiNzE5YmYwYzExN2YzZDVkYjJjZTAyYmRlYmRkZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GtXAGXglHXA1l8ihFG4pl22yiZXt0wMeuPyH6ALC8XE)

not selected yet. click the model to select.

**Comment by sontjer** [comment]
Oops, my bad... it works fine now.
