### ISSUE TITLE
第三章语音，第12小节自然语流中的强读与弱读现象中，缺少了需要标记的内容

### ISSUE THREAD

**Issue by yongsheng725** [xiaolai/everyone-can-use-english#2]
笑来老师，此小节提到：这段录音中所有被强读的词汇在以下的文本中被加重标记。
但这段文字下的文本并没有被标记有不同的内容。
Community service is an important component of education here at our university. We encourage all students to volunteer for at least one community activity before they graduate.
谢谢老师。

**Comment by xiaolai** [comment]
哈哈，既然开源了，你试试标记一下，提交 PR 罢。
