### ISSUE TITLE
发音评估次数限制

### ISSUE THREAD

**Issue by BlueChallenge** [xiaolai/everyone-can-use-english#202]
Hi @an-lee

发音评估的功能非常实用，帮我揪出好多基础的发音错误，请问如何才能解除这个评估次数限制？谢谢

<img width="417" alt="Screenshot 2024-01-25 at 05 47 37" src="https://github.com/xiaolai/everyone-can-use-english/assets/145031804/54242630-a0cd-4948-8f07-4436624c16d5">

**Comment by an-lee** [comment]
得再等等，收费功能上线才能无限制使用。

**Comment by BlueChallenge** [comment]
> 得再等等，收费功能上线才能无限制使用。

感谢回复，请问有大致的时间计划吗

**Comment by an-lee** [comment]
> 感谢回复，请问有大致的时间计划吗

一两周内会先出一个简单方案
