### ISSUE TITLE
跟读功能问题

### ISSUE THREAD

**Issue by hongjie-xu** [xiaolai/everyone-can-use-english#203]
没有跟读功能，点击跟读进入页面，没有录音键

**Comment by an-lee** [comment]
能多提供些信息吗？比如截图？操作系统？使用的版本？

**Comment by Mathophy** [comment]
点击跟读，录不到声音是什么原因，mac 电脑自身的录音软件是可以录到声音的。

**Comment by an-lee** [comment]
> 点击跟读，录不到声音是什么原因，mac 电脑自身的录音软件是可以录到声音的。

用的版本是最新的 alpha.6 吗？预期是会请求麦克风权限的。

如果用的是最新版但没有请求权限，再提供一下你的 Mac 型号和系统版本。

**Comment by Mathophy** [comment]
谢谢回复。
是版本没升级的原因，已解决。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: an-lee ***@***.***&gt;
发送时间: 2024年1月29日 09:23
收件人: xiaolai/everyone-can-use-english ***@***.***&gt;
抄送: Mathophy ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [xiaolai/everyone-can-use-english] 跟读功能问题 (Issue #203)





  
点击跟读，录不到声音是什么原因，mac 电脑自身的录音软件是可以录到声音的。
  
用的版本是最新的 alpha.6 吗？预期是会请求麦克风权限的。
 
如果用的是最新版但没有请求权限，再提供一下你的 Mac 型号和系统版本。

**Comment by an-lee** [comment]
duplicate #215
