### ISSUE TITLE
【feature】生词本快捷键

### ISSUE THREAD

**Issue by mrguangtu** [xiaolai/everyone-can-use-english#208]
![words book](https://github.com/xiaolai/everyone-can-use-english/assets/30472063/2f6bcb20-4467-4de5-9b3b-a5dcaae4ebd6)
在生词本界面，建议增加快捷键方便复习。

- 空格 - 翻转卡片的正反面
- 方向键，h/l键 - 上一个/下一个卡片

**Comment by hongjie-xu** [comment]
我的生词本不能用

**Comment by mrguangtu** [comment]
> 我的生词本不能用

在跟读训练页面，点单子查一下，查出来了自动进入生词本。
生词本界面里面本身没有增加生词的功能。

**Comment by an-lee** [comment]
ref #597

**Comment by an-lee** [comment]
Finished in [v0.2.4](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.2.4)
