### ISSUE TITLE
everyone-can-use-english/new-edition-drafts 错别字

### ISSUE THREAD

**Issue by zzaabbaa01** [xiaolai/everyone-can-use-english#209]
09-实在特权：但，我们的大脑没办法**像**我们展示这种变化带来的变化，于是，我们不知道发生了任何变化。---向
11-以教促学：优等生是那种记得住老师强调过的重点的学生，中等生是那种**靠**前频繁要求老师划重点的学生，差等生是那种老师平日里强调过、考前划过重点也没用的学生---考
18-通用语法：We are all just prisoners here, of **own** own divce---our

**Comment by an-lee** [comment]
PR instead please
