### ISSUE TITLE
来github割程序员的韭菜了

### ISSUE THREAD

**Issue by 03128crz** [xiaolai/everyone-can-use-english#21]

**Comment by joesonw** [comment]
收税, 收税.

**Comment by rxy8023** [comment]
I don't know what you want to express.buttt,as a keyboard man,you may not understand open source spirit for ever.

**Comment by luminous030** [comment]
学习的事, 怎么能叫割韭菜呢~ 不过确实现在英语水平不高, 很多资料看起来都很费力.

**Comment by xiaolai** [comment]
> _No description provided._

傻逼。

**Comment by xiaolai** [comment]
> 收税, 收税.

傻逼，傻逼。

**Comment by yanabcd** [comment]
哈哈哈

**Comment by yanabcd** [comment]
他的文总是主观臆断太严重,大家有看过天才在左疯子在右吗?
