### ISSUE TITLE
请求地址和TTS请求地址应该填写那个

### ISSUE THREAD

**Issue by jarodlong7788** [xiaolai/everyone-can-use-english#212]
我是直连的API KEY没有经过第三方的中转。
填写这个或者简写都是错误的 https://api.openai.com/v1/audio/speech

**Comment by an-lee** [comment]
不用填

**Comment by jarodlong7788** [comment]
> 不用填

不填写也不行，提示连接错误。我的api里面有充值的。

**Comment by an-lee** [comment]
> > 不用填
> 
> 不填写也不行，提示连接错误。我的api里面有充值的。

连接错误是因为你的网络没有全局代理。后续在 Enjoy 里增加代理设置。

如果你网络环境有困难，可以使用 Enjoy 暂时提供的中转接口 https://enjoy-web.fly.dev/openai ，设置成接口地址就行。
