### ISSUE TITLE
建议：添加计时功能

### ISSUE THREAD

**Issue by PercyAtFj** [xiaolai/everyone-can-use-english#219]
能在系统左下方功能栏加个计时按钮（类似番茄时钟）吗？方便知道自己到底每天有没有够时间，一年有没有1000小时。

**Comment by an-lee** [comment]
看录音时间就可以了？

**Comment by PercyAtFj** [comment]
我指的是花费在这个软件上的时间，如果是能像微信阅读一样，不需要操作就能统计到时长就更好了。😄

**Comment by an-lee** [comment]
光是花费在软件上的时间没有太大意义，目前来说，只有录音时间才是最值得关注的。后续有更多功能的时候，会再考虑细致的时间记录。
