### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by BragJ** [xiaolai/everyone-can-use-english#220]
github账号和学升的账号都无法登录？？？是我安装的问题 ？

**Comment by richardzhangy26** [comment]
me too

**Comment by an-lee** [comment]
能详细描述一下现象吗？卡在哪一步？

**Comment by Nicocoler** [comment]
下载的是Enjoy-win32-x64-0.1.0-alpha.8.zip，解压后直接双击enjoy.exe，git登录时报错：

<ActiveRecord::NotNullViolation:"PG::NotNullViolation: ERROR: null value in column \"name\of relation \"users\" violates not-nullconstraint\nDETAlL: Failing row contains(24001792,null, nullhttps://avatars.githubusercontent.com/u/46590120?v=4, null, user 2024-01-3108:32:24.034013,2024-01-31 08:32:24.0340130.0).\n">

**Comment by an-lee** [comment]
> 下载的是Enjoy-win32-x64-0.1.0-alpha.8.zip，解压后直接双击enjoy.exe，git登录时报错：
> 
> <ActiveRecord::NotNullViolation:"PG::NotNullViolation: ERROR: null value in column "name\of relation "users" violates not-nullconstraint\nDETAlL: Failing row contains(24001792,null, nullhttps://avatars.githubusercontent.com/u/46590120?v=4, null, user 2024-01-3108:32:24.034013,2024-01-31 08:32:24.0340130.0).\n">

看着像是 GitHub 授权失败，没有获取到你 GitHub 的用户信息

**Comment by Nicocoler** [comment]
如何操作能清除授权信息呢，现在点击git登录就报此错误，exe程序重启也没用

**Comment by BragJ** [comment]
我的是mac，同样出现，学升账号登录同样显示未授权，命令行启动的时候，有一个报错,如下

'''
➜  everyone-can-use-english git:(main) yarn install
yarn start:enjoy
➤ YN0000: · Yarn 4.1.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 278ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide next (pf50d7), requested by next-themes.
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (p617e3), requested by vite-plugin-static-copy.
➤ YN0002: │ enjoy@workspace:enjoy doesn't provide vite (pe5759), requested by @vitejs/plugin-react.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 29 packages were added to the project (+ 141.69 MiB).
➤ YN0000: └ Completed in 8s 387ms
➤ YN0000: ┌ Link step
➤ YN0007: │ electron@npm:28.2.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 59s 214ms
➤ YN0000: · Done with warnings in 1m 9s
➜  everyone-can-use-english git:(main) yarn start:enjoy
'''

**Comment by an-lee** [comment]
> 我的是mac，同样出现，学升账号登录同样显示未授权，命令行启动的时候，有一个报错,如下

你是 学升App 的用户吗？

**Comment by Yeeler** [comment]
Same error while using the source code. The POST action to create sessions failed due to 500 error from https://enjoy-web.fly.dev.

**Comment by alexyang-sea** [comment]
我也是同样的问题，都用github登录授权了，但是弹出错误报警，如下：
![1](https://github.com/xiaolai/everyone-can-use-english/assets/137014157/76d160eb-b34c-481e-9482-1f6719108b24)

**Comment by an-lee** [comment]
用 [最新版本](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.9) 再试试看？

**Comment by an-lee** [comment]
> Enjoy-win32-x64-0.1.0-alpha.9 还是有报错 !

到 [个人设置](https://github.com/settings/applications) 下的 `Authorized Oauth Apps` 里找到 Enjoy ，然后 Revoke 一下，再试试看？

**Comment by like223** [comment]
我也遇到了相同的错误
![image](https://github.com/xiaolai/everyone-can-use-english/assets/100948669/d0c6679a-18eb-4b6f-b33b-a416fcfea392)

**Comment by Nicocoler** [comment]
> > Enjoy-win32-x64-0.1.0-alpha.9 还是有报错 !
> 
> 到 [个人设置](https://github.com/settings/applications) 下的 `Authorized Oauth Apps` 里找到 Enjoy ，然后 Revoke 一下，再试试看？

已经试了，但是没效果

**Comment by an-lee** [comment]
> 已经试了，但是没效果

加了些 log，麻烦再试试看？我排查一下

**Comment by Nicocoler** [comment]
> > 已经试了，但是没效果
> 
> 加了些 log，麻烦再试试看？我排查一下

重新Revoke 完之后再登录的，授权登录页面正常，但是现在返回后报错变成下图：
![error](https://github.com/xiaolai/everyone-can-use-english/assets/46590120/2ea9783f-e712-4530-8275-9ca77e823688)

**Comment by an-lee** [comment]
> 重新Revoke 完之后再登录的，授权登录页面正常，但是现在返回后报错变成下图： 

找到原因并已经修复上线，可以再试一下看。

**Comment by Nicocoler** [comment]
> > 重新Revoke 完之后再登录的，授权登录页面正常，但是现在返回后报错变成下图：
> 
> 找到原因并已经修复上线，可以再试一下看。

目前登录正常了
