### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by guoqing-programmer** [xiaolai/everyone-can-use-english#228]
使用Enjoy-0.1.0-alpha.5-Setup.exe.安装，出现报错There was an error while installing the
application. Check the setup log for moreinformation and contact the author.
![image](https://github.com/xiaolai/everyone-can-use-english/assets/75361714/bf7e75b6-e27d-4aed-9037-af64b1ab1b66)

**Comment by an-lee** [comment]
请试试最新版。
