### ISSUE TITLE
发送文字后报错：Connection error.

### ISSUE THREAD

**Issue by cpx2222** [xiaolai/everyone-can-use-english#240]
确认api key可以正常使用，发送文字后报错：Connection error.
<img width="383" alt="截屏2024-01-31 下午10 12 15" src="https://github.com/xiaolai/everyone-can-use-english/assets/19421181/060f9551-ba2f-471d-bdd7-d9637224f79e">
<img width="376" alt="截屏2024-01-31 下午11 10 07" src="https://github.com/xiaolai/everyone-can-use-english/assets/19421181/61836ed4-5916-4a57-85e5-2a14e0d56461">
请问是不是需要填写接口地址？在openAI官网注册的API KEY，在哪里可以查找到那两个接口地址。

**Comment by an-lee** [comment]
接口地址留空就是用官方的接口，可能是因为全局代理对 Enjoy 没有生效。
可以先用 Enjoy 提供的中转接口 https://enjoy-web.fly.dev/openai

或者等等 #238

**Comment by cpx2222** [comment]
谢谢导演，已经完美解决。
