### ISSUE TITLE
`Insufficient Balance` warning message

### ISSUE THREAD

**Issue by lihaokx** [xiaolai/everyone-can-use-english#246]
点击 `Pronunciation Assessment`button 之后，显示 `Insufficient Balance` warning message. 
几点说明：
1. 这个message的出现导致页面冻结，无法下一步操作，只能退出重新点开。
2. 昨天出现了这个问题，今天又不能复现了
3. 版本: [v0.1.0-alpha.6](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.6)
![bug-enjoy](https://github.com/xiaolai/everyone-can-use-english/assets/37116651/697c00fa-e58b-4e14-845a-65b506d7fd0c)

**Comment by an-lee** [comment]
发音评估 是收费服务，充值功能开发好之前会限制使用。`Insufficient Balance`  就是字面意思，体验金用完，余额不足了。

不过页面冻结是什么意思？是软件卡死了吗？

另外现在最新版是 [v0.1.0-alpha.8](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.8) 了，推荐升级。软件目前还在早期开发阶段，版本发布会比较频繁，而且不一定会兼容旧版本，推荐及早更新。

**Comment by lihaokx** [comment]
> 不过页面冻结是什么意思？是软件卡死了吗？

是的，卡死了，只能叉掉。

我刚刚更新到最新版本了，谢谢你们

**Comment by an-lee** [comment]
如果再出现卡死，麻烦另外开 issue 再反馈。感谢。
