### ISSUE TITLE
苹果电脑终端显示已经安装了ffmpeg，但是在enjoy上查找，还是查找不到。

### ISSUE THREAD

**Issue by Zoe201306** [xiaolai/everyone-can-use-english#259]
![截屏2024-02-04 13 53 57](https://github.com/xiaolai/everyone-can-use-english/assets/56911497/1e8694c0-7f4b-43c9-9369-c1c85fa2df08)
![截屏2024-02-04 13 54 44](https://github.com/xiaolai/everyone-can-use-english/assets/56911497/8869fb6e-078f-4458-bdec-d46e83c3a433)
已经在终端上重新安装了很多次，都没有用。

**Comment by an-lee** [comment]
请下载最新版，已经不需要安装 ffmpeg 了
