### ISSUE TITLE
语言转文本功能间歇性失灵

### ISSUE THREAD

**Issue by zhouartisan** [xiaolai/everyone-can-use-english#268]
升级到了9.0版本，非常好用，就是语音转文本功能时而有用、时而失灵。由于笔记本显卡太弱，服务选择的是cloudflare（本地模型已经是下载的最小的模型仍然用不了）。报错会有两种不同的提示。有时重启软件又会成功。
提示一：切换到另一个更小的模型以加快速度。
提示二：connet etimedout 172.67.151.244:443。

**Comment by zhouartisan** [comment]
![Uploading 1.png…]()

**Comment by an-lee** [comment]
提示 1 文案有误，已修改。
提示 2 就是网络连接失败了，应该是网络问题。
