### ISSUE TITLE
使用对话报错“a padding to disable MSlE and Chromefriendly error page”

### ISSUE THREAD

**Issue by Fizz0x11** [xiaolai/everyone-can-use-english#271]
已设置openai key，语音使用cloudflare AI
报错：
![11](https://github.com/xiaolai/everyone-can-use-english/assets/49180194/ab11367d-2af3-404b-a36f-2e92256e3334)

404 <html> <head><title>404 NotFound</title></head> <body><center><h1>404 Not Found</h1></center> <hr><center>nginx</center> </body> </html>   <!-- a padding todisable MSlE and Chrome friendly error page

**Comment by an-lee** [comment]
用的 openai key 是中转的吗？是不是配的中转网址配错了？

**Comment by Fizz0x11** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Fizz0x11** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
