### ISSUE TITLE
无法使用音标和翻译功能

### ISSUE THREAD

**Issue by J-xiaodan** [xiaolai/everyone-can-use-english#282]
![WechatIMG299](https://github.com/xiaolai/everyone-can-use-english/assets/59227228/fcdd6373-9ce2-410f-85e7-b42f35556330)
![WechatIMG300](https://github.com/xiaolai/everyone-can-use-english/assets/59227228/c1db29aa-0375-4bba-b5ca-229a2b562cf6)

**Comment by an-lee** [comment]
软件设置 -> 默认AI引擎 选的是哪个？

**Comment by J-xiaodan** [comment]
open AI

**Comment by an-lee** [comment]
> open AI

配了接口地址吗？是不是配得有问题？智能助手用得正常吗？

**Comment by J-xiaodan** [comment]
其他功能都正常使用，就是音标和翻译不行

**Comment by an-lee** [comment]
请更新至最新版。
