### ISSUE TITLE
chapter2 中引用了歌德的一句话，其英文译文是否有误？

### ISSUE THREAD

**Issue by KevinWangJc** [xiaolai/everyone-can-use-english#303]
[chapter2](https://github.com/xiaolai/everyone-can-use-english/blob/main/book/chapter2.md) 中写到：

> 原文是德文，英文译文是：“Whoever is a girl does not want to be loved, and whoever is a boy does not want to be royal to his lover.”

royal 指的是“王室的”，我读到这句译文时，本以为 royal 是 loyal 的笔误，就去查了一下。发现知乎上对此有讨论：[哪个少女不怀春,哪个少年不钟情？——郭沫若先生不小心看错royal 成loyal才有此翻译么？](https://www.zhihu.com/question/268075826)

仔细想了想，这句英文直译过来确实和原意相反。希望老师有时间能确认下，谢谢。

**Comment by xiaolai** [comment]
我正在写新版了，15 年前的旧版，可以暂时放在一边了。另外，这个引用直接删掉，也不影响原内容。
