### ISSUE TITLE
我觉得所有项目都填写完毕了，运行了alpha9.0后的提示还是错误的

### ISSUE THREAD

**Issue by lvdan0129** [xiaolai/everyone-can-use-english#305]
404 <html> <head><title>404 NotFound</title></head> <body> <center><h1>404 Not Found</h1></center> <hr><center>nginx</center> </body> </html>    <!-- a padding todisable MSlE and Chrome friendly error page --

![714eedafa324af86724b686f7da72ba](https://github.com/xiaolai/everyone-can-use-english/assets/50976076/5cb85ad4-2a22-4632-8b96-e47bc940dc47)

**Comment by an-lee** [comment]
接口地址你填了啥？应该填错了吧

**Comment by lvdan0129** [comment]
ldsimple0129
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaolai/everyone-can-use-english"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaolai/everyone-can-use-english] 我觉得所有项目都填写完毕了，运行了alpha9.0后的提示还是错误的 (Issue #305)





 
Closed #305 as completed.

**Comment by lvdan0129** [comment]
ldsimple0129
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "xiaolai/everyone-can-use-english"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaolai/everyone-can-use-english] 我觉得所有项目都填写完毕了，运行了alpha9.0后的提示还是错误的 (Issue #305)





 
Closed #305 as completed.

**Comment by lvdan0129** [comment]
ldsimple0129
***@***.***




&nbsp;
