### ISSUE TITLE
过程都正常，但是最后AggregateError是啥意思？

### ISSUE THREAD

**Issue by hpy729** [xiaolai/everyone-can-use-english#311]
前面安装都正常，直到 yarn start:enjoy
提示：
❌ Error: AggregateError

求大佬帮助，感激不尽！
![20240214_213817](https://github.com/xiaolai/everyone-can-use-english/assets/48587215/2738a81b-7de7-49c2-8457-79247b90b817)

**Comment by an-lee** [comment]
是下载出错了。

可以单独跑一下

```bash
yarn workspace enjoy download
```

出错了就再试几次。

**Comment by hpy729** [comment]
试了多次，问题依旧，求助！真的很想跟上老师的步骤去学习！
![image](https://github.com/xiaolai/everyone-can-use-english/assets/48587215/e62ec6cb-c43d-42ec-a296-d2428120cfff)

**Comment by an-lee** [comment]
拉一下最新代码再试试看。 log 里增加了更多的说明，如果还是下载失败，可以按照 log 里的下载地址和保存地址，手动下载一下相应文件。
