### ISSUE TITLE
关于Display IPA的问题

### ISSUE THREAD

**Issue by yanyinn** [xiaolai/everyone-can-use-english#314]
版本：v0.1.0-alpha.9

我自己有gpt4版本的api-key，可以在AI Assistant中正常使用，但是如果想“Display IPA”（图1），就会显示失败(图2)，termianl中的log信息为图3。

如果换成EnjoyAI，就没有问题，不过好像有使用次数？可能使用了10次后，再想"Display IPA"，就会显示“Generating IPA”, 持续1分钟左右，然后也会显示失败。

图1
<img width="778" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/109458303/ae86b962-2b4d-4020-8ace-e026340bd822">

图2
<img width="350" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/109458303/62758651-c422-46ff-9ad7-311e1a84e2b6">

图3
<img width="682" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/109458303/dd33d753-5b11-45d6-83d4-b75fe0204a6d">

**Comment by an-lee** [comment]
可以下载最新版本再试试，会显示具体的错误原因

**Comment by yanyinn** [comment]
版本：v0.1.0-alpha.12

<img width="1392" alt="Screenshot 2024-02-22 at 6 40 00 AM" src="https://github.com/xiaolai/everyone-can-use-english/assets/109458303/625df6e3-e067-40a5-80d8-b244a81d48f2">

**Comment by an-lee** [comment]
> 版本：v0.1.0-alpha.12

你应该是用了 `gpt-4` 模型，这个模型不支持 json 返回格式，可以在软件设置里选 `gpt-4-preview-1106`。

下个版本会修复这个问题，自动适配模型。

**Comment by yanyinn** [comment]
可以了，感谢导演🙏
