### ISSUE TITLE
点击文字生成语音时没有出现声波图，而是出现横线

### ISSUE THREAD

**Issue by cpx2222** [xiaolai/everyone-can-use-english#333]
点击文字生成语音时没有出现声波图，而是出现横线，请问时哪里设置不对吗？
<img width="736" alt="截屏2024-02-20 上午11 19 28" src="https://github.com/xiaolai/everyone-can-use-english/assets/19421181/3ae1b140-3da4-43f0-9440-563aa503e52a">

**Comment by v5368965** [comment]
同问

**Comment by an-lee** [comment]
有 bug，修好了，请重新下载： https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.12
