### ISSUE TITLE
can no change to music

### ISSUE THREAD

**Issue by lyq760208** [xiaolai/everyone-can-use-english#334]
升级为11的新版本后，语音转换时会报错。求助

<img width="338" alt="acbf4061de02d26d595580ef8209239" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/49b9074f-7c2d-48ba-b9ac-2e305d2c2e4f">
<img width="338" alt="acbf4061de02d26d595580ef8209239" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/c24603a3-ef42-4d8a-bf00-dd93bf611a2d">

**Comment by an-lee** [comment]
有 bug，修好了，请重新下载： https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.1.0-alpha.12
