### ISSUE TITLE
enjoy alpha11 install question

### ISSUE THREAD

**Issue by lyq760208** [xiaolai/everyone-can-use-english#336]
重新enjoy alpha11下载后，安装出现如下问题：
<img width="514" alt="d07c7c40231cc7f3f0abfa7a0c3ca71" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/0f619554-4a61-4536-9c1d-860d7efc6a77">
原来的enjoy 0.9的版本，重新安装后都正常，没有发现问题。
请问是什么问题？谢谢！！！

**Comment by an-lee** [comment]
Open Setup Log 点击看看 log 有啥？

你的电脑系统版本是什么？

另外试试最新的 alpha.12 版本。

**Comment by lyq760208** [comment]
> Open Setup Log 点击看看 log 有啥？
> 
> 你的电脑系统版本是什么？
> 
> 另外试试最新的 alpha.12 版本。

打不开log,但是下载了alpha.12的，一切oK,谢谢！！感谢神速回复！
