### ISSUE TITLE
使用不了 发音评估 功能

### ISSUE THREAD

**Issue by yemao-Y** [xiaolai/everyone-can-use-english#340]
![微信截图_20240220132229](https://github.com/xiaolai/everyone-can-use-english/assets/56233801/6089ed93-590d-42ab-8343-b483cdf2b42f)

**Comment by michaelzhihua** [comment]
me too

**Comment by an-lee** [comment]
这个功能目前有每天使用次数限制，余额不足也会报错。

错误信息没显示是 bug，下个版本会修复。

**Comment by an-lee** [comment]
请更新至最新版
