### ISSUE TITLE
“正在解码波形”总是在转

### ISSUE THREAD

**Issue by michaelzhihua** [xiaolai/everyone-can-use-english#345]
已安装12版本，“正在解码波形”总是在转，无法练习，求速解决

**Comment by an-lee** [comment]
如果是时长比较长的音频，解码需要一些时间的。

等了多久？是每个音频都这样吗？

**Comment by michaelzhihua** [comment]
刚看到，不好意思！这个问题解决了！谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaolai/everyone-can-use-english"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月24日(星期六) 上午7:26
***@***.***&gt;;
抄送:&nbsp;"winter ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaolai/everyone-can-use-english] “正在解码波形”总是在转 (Issue #345)





 
如果是时长比较长的音频，解码需要一些时间的。
 
等了多久？是每个音频都这样吗？
