### ISSUE TITLE
更新到 enjoy版本alpha 12后的问题

### ISSUE THREAD

**Issue by Yayamini** [xiaolai/everyone-can-use-english#348]
您好，

我今晚更新到 enjoy的 Alpha 12 版本后，打开一看，历史的 AI conversion 记录都消失了，请问还有恢复的可能吗？

我一直是用 mixin 账号登录，但我留意到这个版本的登录方式除了mixin外还有学升、github账号，所以我尝试用学升的手机账号登录，因为学升与mixin 对应绑定的都是同一个手机号码，本能想测试下是否实现了手机号码的统一同步。

我 使用学升的手机号码登录enjoy，发现没有历史记录后，先退出账号，再使用原来的mixin 账号登录，但依然是没有历史记录。Enjoy目前的更新频次挺快的，但我不确定是这个历史记录是没有实现云服务器同步吗？
如果历史记录是本地保存，那么具体应该如何操作才能恢复数据呢?

谢谢

**Comment by an-lee** [comment]
所有数据都是本地储存的，都在资源库 `EnjoyLirary` 文件夹里。

你在 `软件设置` 里能找到 `资源库保存路径`，这个就是你目前登录的资源库文件夹。点`打开`可以打开这个文件夹

然后你在你电脑里再搜一下有没有另一个 `EnjoyLirary` 的文件夹，找到把，把文件夹里的所有文件拷贝并覆盖至你新的文件夹里。

重启 Enjoy，应该就可以了。

**Comment by an-lee** [comment]
可以再参考 [文档](https://1000h.org/enjoy-app/settings.html#%E8%B5%84%E6%BA%90%E5%BA%93%E4%BF%9D%E5%AD%98%E8%B7%AF%E5%BE%84)
