### ISSUE TITLE
可以增加一下本地TXT文件吗？

### ISSUE THREAD

**Issue by newzyb** [xiaolai/everyone-can-use-english#362]
手中有一些原版书的资源，但是，现在软件只能添加URL地址，是否增加可以添加本地TXT格式的文件？

**Comment by an-lee** [comment]
目前仅支持添加本地音频、视频。

文本阅读功能也在开发计划中，要再等等。

**Comment by newzyb** [comment]
非常感谢导演在百忙的回复，既然已经在开发中了，那就在等等。
