### ISSUE TITLE
Request fail with status code 503

### ISSUE THREAD

**Issue by langlango** [xiaolai/everyone-can-use-english#372]
Enjoy升级alpha12，STT AI service选的是cloudflare AI，语音转换文本功能无法使用，转换过程报错503，请问该如何解决？
![enjoy2](https://github.com/xiaolai/everyone-can-use-english/assets/113528632/c84edf16-860c-452a-9400-8c2fb1d6423d)

![enjoy1](https://github.com/xiaolai/everyone-can-use-english/assets/113528632/df0339c6-a43b-4123-876b-ff500de3ec7b)

**Comment by an-lee** [comment]
cloudflare 提供的免费服务有算力限制，是不是提交了比较大的音频？可以多试几次，或者改用其他 STT 服务。

**Comment by langlango** [comment]
应该是算力限制原因，我今天尝试了小一些的音频，可以成功转换了。之前转换失败的音频有290个单词。
