### ISSUE TITLE
 CAN NOT OPEN

### ISSUE THREAD

**Issue by lyq760208** [xiaolai/everyone-can-use-english#383]
ENJOY12,使用正常。
下载了enjoy13，的安装程序，安装之后，无法打开，双击程序图标无反应，我的操作系统是windows10.,请问是什么原因？谢谢！！
打开设置检查，版本有更新到enjoy13.
<img width="392" alt="enjoy图片" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/a239f7c1-5943-48c0-9462-decf5a47d706">

把enjoy13卸载后，重新装enjoy12后能正常使用。谢谢！！

**Comment by an-lee** [comment]
是下载的这个 https://github.com/xiaolai/everyone-can-use-english/releases/download/v0.1.0-alpha.13/Enjoy-0.1.0-alpha.13-Setup.exe 吗？

安装成功的话应该不是这个图标。

**Comment by an-lee** [comment]
暂时不确定是什么原因。可以试试卸载后重新安装，或者试试这个[免安装版本](https://github.com/xiaolai/everyone-can-use-english/releases/download/v0.1.0-alpha.13/Enjoy-win32-x64-0.1.0-alpha.13.zip)，下载解压之后直接打开

**Comment by lyq760208** [comment]
免安装的版本 enjoy13也下载了，解压了，打开后还是没反应！先装回enjoy12的用，只是在网上买的openAI的key,转成音标的功能没法用了，显示令牌到期了。想用一用enjoy13,哈哈！
<img width="493" alt="ENJOY" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/bab5fdbb-d875-4172-8b68-8e3799a7369c">
这个图是解压后的enjoy13!打开，没动静！

**Comment by lyq760208** [comment]
今天再次打开安装文件enjoy13，居然安装成功！！！
<img width="568" alt="微信图片_20240305144824" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/713025c6-ef40-4592-9d63-6bd1e0f4ad26">
很开心！！！
还有一个问题：
<img width="848" alt="123" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/170c1d9a-c90b-4700-810e-e982ee190869">
如何设置，可以把语音转文本，变成一句一句的短一点的句子。
谢谢！！

**Comment by lyq760208** [comment]
找到了设置的方法了：
打开enjoy
1、选择下图中的红色部分（充值）
<img width="548" alt="5a0006ed97e2af51f821e89def25fa9" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/9eca0634-98e4-4d30-b4ec-dd521b40610c">
2、选择AZURE AI
<img width="551" alt="4376479a7640a6d29c49c937eb28f02" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/321fa3a1-b06f-422e-ab34-862089571601">
3、填入邮箱：选择一个支付的方式，我是用微信，很方便！
<img width="379" alt="87d2d87e179307e978a2b14ddfe9179" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/50ae8736-d4d7-4627-b458-a98969f91a49">
谢谢笑来老师，谢谢李安导演！！

**Comment by lyq760208** [comment]
充值之后的语音转文本就变成这样了：
<img width="869" alt="69961754c20a26d8646350dab02d00a" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/cfcb45a4-19f8-46ec-af0e-aca520ff1ae2">
真好！！
