### ISSUE TITLE
可以增加更多快捷键吗？譬如“播放下一句”的快捷键

### ISSUE THREAD

**Issue by anzchy** [xiaolai/everyone-can-use-english#386]
如题，目前主要用鼠标移动点击，不够便捷，尤其是用走步机+升降桌，有了快捷键，就可以映射到鼠标侧边键上，方便用鼠标操作。
目前，“播放”快捷键已经有了，“播放下一句”也很刚需。

**Comment by an-lee** [comment]
有计划的，再等等。

**Comment by an-lee** [comment]
added in #416

**Comment by an-lee** [comment]
[v0.2.0](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.2.0)
