### ISSUE TITLE
1000h 小喇叭图标与音标标注

### ISSUE THREAD

**Issue by bluechallenge** [xiaolai/everyone-can-use-english#395]
以 [1.1.3 美式语音标注](https://1000h.org/sounds-of-english/01-3-us-phonemes) 为例，音标是英音在前、美音在后，小喇叭是美音在前、英音在后。是否有可能微调，使音标标注和小喇叭图标顺序一致？

<img width="707" alt="Screenshot 2024-03-07 at 21 10 25" src="https://github.com/xiaolai/everyone-can-use-english/assets/145031804/f81587a6-42c5-4fe6-a958-a3abc122c218">

**Comment by xiaolai** [comment]
整个教程更新了。
