### ISSUE TITLE
Enjoy doesn't work on Ubuntu

### ISSUE THREAD

**Issue by worras2019** [xiaolai/everyone-can-use-english#396]
Enjoy doesn't work on Ubuntu. Please provide a guidance on running it on Ubuntu.

**Comment by an-lee** [comment]
How come? I develop it on Ubuntu.

Just download the [.deb file](https://github.com/xiaolai/everyone-can-use-english/releases/download/v0.1.0-alpha.13/enjoy_0.1.0-alpha.13_amd64.deb) and install.
