### ISSUE TITLE
发音评估时候报错：Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by careyee** [xiaolai/everyone-can-use-english#398]
mac电脑：报错提示
Client network socket disconnected before secure TLS connection was established

**Comment by an-lee** [comment]
应该就是网络问题

**Comment by careyee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by careyee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
