### ISSUE TITLE
遇到长文本，生成音标的功能会出错

### ISSUE THREAD

**Issue by pierrelzw** [xiaolai/everyone-can-use-english#409]
因为 macos 系统原因，我这里只能用云服务进行语音转换。
转换出来的文本，常常整篇是一大段文字。表现为：进入跟读页面后，只有一个页面（待补充图片）

这种情况下生成音标，要么出错，要么缺失

**Comment by an-lee** [comment]
Azure AI 的效果应该是比较稳定的。你是在用 cloudflare AI 吧？

**Comment by an-lee** [comment]
[v0.2.0](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.2.0)
