### ISSUE TITLE
“标注音标” 的来源？有些似乎有错

### ISSUE THREAD

**Issue by pierrelzw** [xiaolai/everyone-can-use-english#410]
比如下面的 restaurant 和 comparatively
 /ˈres.tə.rɑːnt/ 和 /kəmˈper.ə.t̬ɪv.li/
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/51ac5acc-f1f7-451c-8156-aede79201757)

**Comment by an-lee** [comment]
目前是 openAI 生成的，确实有错漏。下个版本会用别的方法优化一下。

**Comment by an-lee** [comment]
[v0.2.0](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.2.0)

音标后续还会继续优化。
