### ISSUE TITLE
可否增加“enjoy app”语速调整功能的范围

### ISSUE THREAD

**Issue by plutomiao** [xiaolai/everyone-can-use-english#411]
问题描述：在当前版本的“enjoy”软件中，语速调整功能的范围限制在0.8到1倍之间。对于英语学习初学者，特别是小孩来说，0.8倍速的语速有时也感觉过快，他们难以跟上和理解。

建议：希望“enjoy”软件能增加更广范围的语速调整选项，特别是将最低倍数降至0.3或0.5，从而提高学习体验。

谢谢

**Comment by an-lee** [comment]
限制到 0.8 是故意的。初学者觉得快是正常的，多听几次。语速慢了对学习效果并没有帮助，语速过慢了，声音也会变形。
