### ISSUE TITLE
413 maximum content size limit exceed

### ISSUE THREAD

**Issue by jackli100** [xiaolai/everyone-can-use-english#413]
![image](https://github.com/xiaolai/everyone-can-use-english/assets/148944467/436a1021-72fc-40a9-984c-785e7ff57c6b)
使用OpenAI官方的whiper进行翻译报错，十五分钟的视频也会显示该报错

**Comment by jackli100** [comment]
说错了，应该是transcribe转录，stt服务

**Comment by an-lee** [comment]
这就是 OpenAI 的报错，上传的文件太大了。
