### ISSUE TITLE
feature 建议：wav/mp3音频下载功能

### ISSUE THREAD

**Issue by pierrelzw** [xiaolai/everyone-can-use-english#434]
上周末茶话会分享后，发现很多人有下载 mp3 的需求，不管是 AI 生成的 mp3，还是自己的录音。
我写了教程，让大家去 “资源库保存路径” 里找：https://mp.weixin.qq.com/s/ZNhqx86fnDmLw45EZyT_vw

不过这个有风险：
今天，我没有修改文件，只是复制了几个文件并重命名复制后的文件（依然在 audios 目录下）
，enjoy 提示数据库被破坏，需要清空所有数据
![Uploading image.png…]()

**Comment by an-lee** [comment]
已经开发好了，马上发新版本。

**Comment by an-lee** [comment]
[v0.2.0](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.2.0)
