### ISSUE TITLE
Shadowing audio 界面交互bug

### ISSUE THREAD

**Issue by Yayamini** [xiaolai/everyone-can-use-english#447]
Hi，

如标题所述，Shadowing audio 界面中左上角，语音文本相关模块展示受限，右侧展示句子的模块也一样，麻烦排查此bug问题。如下是我这边设备的相关情况：
电脑：MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)
Version:12.7.3
Processor：2 GHz Dual-Core Intel Core i5
安装的Enjoy 版本：[v0.2.0](https://github.com/xiaolai/everyone-can-use-english/releases/latest)
[Intel 芯片版本(x64)](https://github.com/xiaolai/everyone-can-use-english/releases/download/v0.2.0/Enjoy-0.2.0-x64.dmg)

附上app界面兼容异常的截图，如需了解进一步资料，请随时留言

谢谢

![Uploading 2490339782.png…]()

**Comment by Yayamini** [comment]
![Uploading 2490339782.png…]()

**Comment by Yayamini** [comment]
![Uploading 2490339782.png…]()

**Comment by Yayamini** [comment]
另外，再补充一个提问
在 pronunciation assessment 界面如何返回上一页呢？目前都是关掉整个app，再重启 enjoy 才能继续使用

**Comment by an-lee** [comment]
> 附上google drive 链接 https://drive.google.com/file/d/1_RB4Ucn3-F9BGUqc76VQ_jSrvf2blmJ_/view?usp=sharing

看到了，低分辨率屏幕下，这个布局是有问题。下个版本会优化。

> 在 pronunciation assessment 界面如何返回上一页呢？目前都是关掉整个app，再重启 enjoy 才能继续使用

上方中间不是有向下的箭头吗？或者点一下上面空白模糊区域也能返回。甚至按下 Esc 都可以返回。

**Comment by Yayamini** [comment]
> > 附上google drive 链接 https://drive.google.com/file/d/1_RB4Ucn3-F9BGUqc76VQ_jSrvf2blmJ_/view?usp=sharing
> 
> 看到了，低分辨率屏幕下，这个布局是有问题。下个版本会优化。
> 
> > 在 pronunciation assessment 界面如何返回上一页呢？目前都是关掉整个app，再重启 enjoy 才能继续使用
> 
> 上方中间不是有向下的箭头吗？或者点一下上面空白模糊区域也能返回。甚至按下 Esc 都可以返回。

Hi，
不知道是什么原因，我电脑安装的 V0.2.2 版本 pronunciation assessment 界面中，没有你提到的下箭头，点击空白模糊区域也没有触发返回动作呢
截图 Google drive：https://drive.google.com/file/d/1lRkx5Jv_tPALcumk4ciY2doGc3PSSqhB/view?usp=sharing

**Comment by an-lee** [comment]
![image](https://github.com/xiaolai/everyone-can-use-english/assets/22209056/d8b1a479-5ef1-4b41-a855-ec1174b3c464)

正常显示应该是这样的。即使窗口缩放至最小，应该也能正常显示才对。

你的电脑型号是什么？试试将 Enjoy 窗口全屏看看？
