### ISSUE TITLE
有些句子被切太碎了，如何把它们变成一句话？

### ISSUE THREAD

**Issue by pierrelzw** [xiaolai/everyone-can-use-english#448]
edit 可以把两段音频合成一段，不过对应的英文和音标没有合并

!![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/a6447dd9-370c-450f-8dea-abcf221bd072)

**Comment by an-lee** [comment]
你的截图总是没上传成功。不明白你说的意思。

**Comment by pierrelzw** [comment]
> 你的截图总是没上传成功。不明白你说的意思。

重新上传了

**Comment by an-lee** [comment]
为啥要合并起来，本来就是两个句子。编辑是为了微调，不能合并。

**Comment by pierrelzw** [comment]
> 为啥要合并起来，本来就是两个句子。编辑是为了微调，不能合并。

的确合并不是强需。。。
