### ISSUE TITLE
 windows系统下无法安装！

### ISSUE THREAD

**Issue by lyq760208** [xiaolai/everyone-can-use-english#458]
<img width="960" alt="2 0报错1" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/63a667e2-b1e7-4588-8050-2fdd3991d052">
<img width="960" alt="2 0报错2" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/71c61df1-2c03-4ed5-9586-5c1e02bdc665">
不知道是啥原因，请指点！！谢谢！

**Comment by an-lee** [comment]
应该是某些缺少某些依赖，尝试一下

1. 升级系统，自动更新如果有可更新的就更新一下；
2.  https://aka.ms/vs/17/release/vc_redist.x64.exe 下载这个安装一下，然后再试试
