### ISSUE TITLE
充值后余额一直无变化

### ISSUE THREAD

**Issue by yuquan-zhang** [xiaolai/everyone-can-use-english#470]
我通过账户界面充值了2个pUSD，但充值完成后，余额过大半天都没有变化。不知道是充值不成功，还是到账很慢。如果说不成功，我的钱已经从钱包中扣掉了，如果说到账很慢，那也太慢了，都大半天了。有谁知道是什么原因吗？

<img width="1476" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/23272538/50f72c52-c48d-43d1-bfaf-45414b0c527a">

**Comment by an-lee** [comment]
把你转账记录发给我看看 Mixin ID: 1051445

**Comment by an-lee** [comment]
是有个服务挂了。现在已经恢复正常。
