### ISSUE TITLE
体验优化建议

### ISSUE THREAD

**Issue by theWorkFsz** [xiaolai/everyone-can-use-english#471]
刚体验了一下 ，这个 app 确实很有意思，不过有几点小建议

1. 字幕跟随高亮单词时样式优化
![image](https://github.com/xiaolai/everyone-can-use-english/assets/45343728/74b7a05c-26d3-4f11-a88f-17cad67ab187)

目前只有文字标红高亮，观感上相当不明显，建议可以给一个 border 将其圈起来，视觉上会比单纯文字高亮更明确，
此外单词选中时可以看到单词直接贴到边了，建议给单词的添加 padding，给出一些留白，视觉上观感会更好

一个效果参考例子
https://jsfiddle.net/gyzrxb7e/2/

2. 播放器没有音量调整？
我似乎没有找到音频播放的时候有调节音量的地方……

**Comment by an-lee** [comment]
音量控制确实还没有，后续再搞一下吧。
