### ISSUE TITLE
feature:能否在 Audio Player 处增加快捷键绑定用于循环、Prev、Next segment

### ISSUE THREAD

**Issue by slarkvan** [xiaolai/everyone-can-use-english#479]
类似于这种

![image](https://github.com/xiaolai/everyone-can-use-english/assets/131340443/e9f69619-eedd-476e-a6da-125eb6891054)

主要是为了对英文句子进行反复肌肉训练，键盘就可以控制 loop/prev/next 

如果需求 OK 且您没空的话，我可以提个 PR

期待你的回复

**Comment by an-lee** [comment]
目前已经有一部分快捷键了，请查询 软件设置/快捷键。后续会添加更多快捷键

**Comment by slarkvan** [comment]
刚刚看到了已有的 Hotkeys 功能了。
有一点我觉得可以改进的是当前 Hotkeys Player 部分改下默认值。目前的 Player 区域的 Hotkeys 感觉一只手搞不过来。

我准备做如下修改
1. Hotkeys 默认值修改成 `a`、`s`、`d`、`space`、`q`、`c`、`v`
- `a`: 上一个
- `s`:  重复
- `d`: 下一个
- `space`: 播放/暂停
- `q`:  开启/ 关闭自动暂时
- `c`:  Start or Stop Recording
- `v`:  Play or Pause Recording

2. 提供用户可以自定义 Hotkeys 的功能


还想请教下您的建议

**Comment by an-lee** [comment]
默认值先不要改。

自定义 hotkeys 是计划要做的。

**Comment by slarkvan** [comment]
自定义 hotkeys，有空帮忙 review 下
https://github.com/xiaolai/everyone-can-use-english/pull/494

**Comment by an-lee** [comment]
#496 已合并
