### ISSUE TITLE
Feature: Add github device workflow auth

### ISSUE THREAD

**Issue by bxb100** [xiaolai/everyone-can-use-english#480]
I want to add device flow[^1], can I take a PR? @an-lee 

[^1]: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#device-flow

**Comment by an-lee** [comment]
PR is always welcome :)

**Comment by bxb100** [comment]
seems like much effort on the server side, but not open source, so I quit
