### ISSUE TITLE
提示添加视频失败

### ISSUE THREAD

**Issue by R2vix** [xiaolai/everyone-can-use-english#482]
修改了资源库路径，重启软件且重启电脑后，从视频添加网络资源仍然提示添加视频失败。
1. 从报错信息看，资源库路径似乎没修改成功
2. 添加的网络资源URL：https://www.ted.com/talks/anthony_tan_and_amane_dannouni_want_to_succeed_in_business_find_a_problem_to_solve
3. 
![image](https://github.com/xiaolai/everyone-can-use-english/assets/162585942/da3385eb-8d73-4b8e-944d-d1658313cc61)
![image](https://github.com/xiaolai/everyone-can-use-english/assets/162585942/8368cbfe-e6c1-414e-957d-b969b0d7d75d)

**Comment by an-lee** [comment]
1. 资源库路径已经修改成功；
2. Tedtalk 链接目前不支持下载视频（图片显示只下载了网页，所以不支持添加）。

**Comment by R2vix** [comment]
我尝试添加Youtube视频也不成功：
![image](https://github.com/xiaolai/everyone-can-use-english/assets/162585942/5fa5e159-6325-4e29-aa04-fc9541fe37ae)

**Comment by an-lee** [comment]
应该是因为 youtubedr 出 bug 了，已经升级版本( https://github.com/xiaolai/everyone-can-use-english/pull/460 )，等 Enjoy 发新版吧。
