### ISSUE TITLE
整句标识音标时的重音符

### ISSUE THREAD

**Issue by bluechallenge** [xiaolai/everyone-can-use-english#484]
导演好，Enjoy v0.2.2支持整句标识音标，想确认其中的重音符是什么意思？目前看到部分单词重音的标注与Cambridge Dictionary有些出入，例如：

**例一**：重音符后移或前移

<img width="962" alt="Screenshot 2024-04-02 at 06 54 54" src="https://github.com/xiaolai/everyone-can-use-english/assets/145031804/0500ebcb-4ff1-4823-be35-8bc5f2b5cd42">

Cambridge Dictionary是这么标注美式音标的：
[liking](https://dictionary.cambridge.org/dictionary/english/liking) /ˈlaɪ.kɪŋ/，
[banana](https://dictionary.cambridge.org/dictionary/english/banana) /bəˈnæn.ə/

**例二**：Whoa, all, done 这三个单词本身是没有重读音节，Enjoy标注重音的作用是什么？

<img width="295" alt="Screenshot 2024-04-03 at 11 31 51" src="https://github.com/xiaolai/everyone-can-use-english/assets/145031804/3af06e67-fd3e-4f29-a3e8-bd321c47ace8">

感谢

**Comment by xiaolai** [comment]
1. 整句音标，是机器生成的，与 CEPD 的差异在于，重音符号放在元音之前，而不是整个音节之前。
2. 单音节词汇，本身就是带重音的，只不过，在词典里，由于只有一个音节，所以省去了标注。

**Comment by bluechallenge** [comment]
谢谢笑来老师，这下清楚了
