### ISSUE TITLE
enjoy桌面显示超出屏幕，页面无法缩小，下面的功能键无法操作

### ISSUE THREAD

**Issue by Zhangjuanlli** [xiaolai/everyone-can-use-english#489]
enjoy桌面显示超出屏幕，页面无法缩小，下面的功能键无法操作
![1712408614502](https://github.com/xiaolai/everyone-can-use-english/assets/68979481/fab056d1-b450-41de-afc6-84d72860d3be)
如图所示
还有如何设置屏幕语言，看到有些同学的是中文，我的是英语，一直没找到设置按钮

**Comment by Zhangjuanlli** [comment]
上图里，下面的选择语速的按钮就看不到了

**Comment by Zhangjuanlli** [comment]
中间录音部分的波形图在录音过程中跳跃幅度很大，有些分散注意力，是否有坑调整得平和点 @lyricat

**Comment by an-lee** [comment]
> 上图里，下面的选择语速的按钮就看不到了

你的电脑分辨率多少？Enjoy 限制了最新小窗口。你可以全屏之后使用。

**Comment by an-lee** [comment]
> 还有如何设置屏幕语言，看到有些同学的是中文，我的是英语，一直没找到设置按钮

软件设置 -> 帐号设置

**Comment by Zhangjuanlli** [comment]
![image](https://github.com/xiaolai/everyone-can-use-english/assets/68979481/420f1eaf-e7a8-49d5-b0cb-bcaf830737e8)
看到回复说是通过软件设置--账号设置，研究了，还是没弄明白，可否在图片中给圈出指示

**Comment by Zhangjuanlli** [comment]
> > 上图里，下面的选择语速的按钮就看不到了
> 
> 你的电脑分辨率多少？Enjoy 限制了最新小窗口。你可以全屏之后使用。

我的分辨率：
<img width="390" alt="1712488704582" src="https://github.com/xiaolai/everyone-can-use-english/assets/68979481/b17905d4-28b3-4bb6-a5bf-ab3579674aeb">
我看电脑可以选择、多少合适：
<img width="410" alt="1712488740477" src="https://github.com/xiaolai/everyone-can-use-english/assets/68979481/faaa299f-ef61-45df-9d41-5fadf57515b9">
另外，现在打开，下面的按钮可以看到了，也就是显示的情况不稳定，前阵子我就发现这个问题，只是当时没有想到求助

**Comment by an-lee** [comment]
> ![image](https://private-user-images.githubusercontent.com/68979481/320276016-420f1eaf-e7a8-49d5-b0cb-bcaf830737e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTU0ODMsIm5iZiI6MTcxMjQ5NTE4MywicGF0aCI6Ii82ODk3OTQ4MS8zMjAyNzYwMTYtNDIwZjFlYWYtZTdhOC00OWQ1LWIwY2ItYmNhZjgzMDczN2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDEzMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZGY4NmM3YzQ5NjczODk3OWZmYTFkNTM4MWZiMDQ1NjA5NTc2NWM0YTAwZDBmMzVmOGQ2ZTgyMzM5MGM5YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRWbrb_Ej-Rm0E-pHMdezd7rG_r-AI3UldhqjhjupHU) 看到回复说是通过软件设置--账号设置，研究了，还是没弄明白，可否在图片中给圈出指示

点 `Account`

**Comment by Zhangjuanlli** [comment]
> > ![image](https://private-user-images.githubusercontent.com/68979481/320276016-420f1eaf-e7a8-49d5-b0cb-bcaf830737e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTU0ODMsIm5iZiI6MTcxMjQ5NTE4MywicGF0aCI6Ii82ODk3OTQ4MS8zMjAyNzYwMTYtNDIwZjFlYWYtZTdhOC00OWQ1LWIwY2ItYmNhZjgzMDczN2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDEzMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZGY4NmM3YzQ5NjczODk3OWZmYTFkNTM4MWZiMDQ1NjA5NTc2NWM0YTAwZDBmMzVmOGQ2ZTgyMzM5MGM5YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRWbrb_Ej-Rm0E-pHMdezd7rG_r-AI3UldhqjhjupHU) 看到回复说是通过软件设置--账号设置，研究了，还是没弄明白，可否在图片中给圈出指示
> 
> 点 `Account`

感谢，语言设置操作成功

**Comment by Zhangjuanlli** [comment]
> > > 上图里，下面的选择语速的按钮就看不到了
> > 
> > 
> > 你的电脑分辨率多少？Enjoy 限制了最新小窗口。你可以全屏之后使用。
> 
> 我的分辨率： <img alt="1712488704582" width="390" src="https://private-user-images.githubusercontent.com/68979481/320277072-b17905d4-28b3-4bb6-a5bf-ab3579674aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODkyNTMsIm5iZiI6MTcxMjQ4ODk1MywicGF0aCI6Ii82ODk3OTQ4MS8zMjAyNzcwNzItYjE3OTA1ZDQtMjhiMy00YmI2LWE1YmYtYWIzNTc5Njc0YWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMjIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYjQzZTIzMmFlZTMzN2FmN2I3NjYwNDJkMzA1Mzc0NjRhZmQ2MThhOTczZGM3MDU2Nzg5NjU0ZDcyYjJkYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-nKg4H1P5CRS7qnKJQ591YufVo2ptPlNk3nA4fV6pk"> 我看电脑可以选择、多少合适： <img alt="1712488740477" width="410" src="https://private-user-images.githubusercontent.com/68979481/320277118-faaa299f-ef61-45df-9d41-5fadf57515b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODkyNTMsIm5iZiI6MTcxMjQ4ODk1MywicGF0aCI6Ii82ODk3OTQ4MS8zMjAyNzcxMTgtZmFhYTI5OWYtZWY2MS00NWRmLTlkNDEtNWZhZGY1NzUxNWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMjIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOWY3OWM2YWRmMzU0NzBlYzkwM2U0ZWM3MzA1NGRlNDc1NWZjMzk4ZDM2MTc2YzczOTM5NGE2Y2Q3ZTg3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vxBqGxSGOVPh3Zr4ysE6DAXqLHnWd7AgjbpErnspQuA"> 另外，现在打开，下面的按钮可以看到了，也就是显示的情况不稳定，前阵子我就发现这个问题，只是当时没有想到求助

全屏设置之后，不方便，影响操作。期待能把屏幕设置成任何大小，

**Comment by an-lee** [comment]
> 全屏设置之后，不方便，影响操作。期待能把屏幕设置成任何大小，

打开之后默认大小应该是 1440x900，最小可以缩放至 1024x768，应该已经够用了。可以试试拖动窗口缩放一下。

**Comment by Zhangjuanlli** [comment]
> > 全屏设置之后，不方便，影响操作。期待能把屏幕设置成任何大小，
> 
> 打开之后默认大小应该是 1440x900，最小可以缩放至 1024x768，应该已经够用了。可以试试拖动窗口缩放一下。

正常情况下，网页页面大小可以调整，可以自由拖动；目前咱们enjoy 的页面只能左右方向上调整宽度，上下的双箭头可以看到，但不起作用，无法调整。桌面无法拖动缩放显示页面。
感恩老师的不断优化迭代工具。

**Comment by Zhangjuanlli** [comment]
![image](https://github.com/xiaolai/everyone-can-use-english/assets/68979481/1665451c-a272-436b-8571-a7761114ee53)
我选中to generate,点击发音，不能完整给出发音

我不断反馈自己使用过程中的问题，期待我们的enjoy早日成长为功能强大的学习英语的好工具
