### ISSUE TITLE
AI生成音频中某些单词的发音似乎和词典发音不一致

### ISSUE THREAD

**Issue by shikongwuwei** [xiaolai/everyone-can-use-english#507]
似乎是对音标的标注有问题
![Snipaste_2024-04-10_15-38-39](https://github.com/xiaolai/everyone-can-use-english/assets/32961399/0a938397-88f1-4b36-9a8d-563cb1563e2c)
![Snipaste_2024-04-10_15-39-47](https://github.com/xiaolai/everyone-can-use-english/assets/32961399/be26707b-2aaf-4128-b8c0-887186f17883)

**Comment by shikongwuwei** [comment]
![Snipaste_2024-04-10_17-46-13](https://github.com/xiaolai/everyone-can-use-english/assets/32961399/f67187a7-1e1e-4083-a79b-6645c76e7c6b)
把这一块去掉，完全是画蛇添足，负优化，对注意力造成了干扰和影响，或者可以允许用户自定义布局。

**Comment by an-lee** [comment]
音标问题在 v0.2.3 做了一定的优化，后续会继续优化。
布局问题也会持续优化。
