### ISSUE TITLE
command not found: zx

### ISSUE THREAD

**Issue by haojiexuexi** [xiaolai/everyone-can-use-english#517]
![WX20240412-132832@2x](https://github.com/xiaolai/everyone-can-use-english/assets/50816451/8ae90a0b-f34e-48a1-8910-92ba4270e0e1)

如图

**Comment by an-lee** [comment]
先 `yarn install` 一下

**Comment by haojiexuexi** [comment]
下载 demg 文件安装搞定了，可能是我的电脑系统版本太低 11.7.10，命令行启动不了…
