### ISSUE TITLE
黑夜模式下，部分颜色依然为黑色

### ISSUE THREAD

**Issue by JIM4ME** [xiaolai/everyone-can-use-english#530]
设备：m2 air 8+256
enjoy版本： 0.2.3

黑夜模式下，自动分析的相关的字体依然是黑色的，看不清楚。

![截屏2024-04-16 09 23 02](https://github.com/xiaolai/everyone-can-use-english/assets/56964139/34003c0b-f8ac-4744-a0b2-3d770ed8a84d)
![截屏2024-04-16 09 23 34](https://github.com/xiaolai/everyone-can-use-english/assets/56964139/9a9784f4-6959-41aa-9262-2e91f9b0f1a7)

**Comment by an-lee** [comment]
Fixed in [v0.2.4](https://github.com/xiaolai/everyone-can-use-english/releases/tag/v0.2.4)
