### ISSUE TITLE
无法退出bug

### ISSUE THREAD

**Issue by JIM4ME** [xiaolai/everyone-can-use-english#545]
有时候会，在点击进入逐句练习时，会出现以下错误提示。然后就直接卡住了，无法点击取消。只能直接退出程序。
<img width="776" alt="截屏2024-04-20 23 45 50" src="https://github.com/xiaolai/everyone-can-use-english/assets/56964139/52bd8588-456c-46db-aa3b-8f2c3b7d58bb">

**Comment by JIM4ME** [comment]
重启后依然会出现

**Comment by an-lee** [comment]
是 TTS 生成的音频文件吗？在对话里，音频能播放吗？

**Comment by JIM4ME** [comment]
> 是 TTS 生成的音频文件吗？在对话里，音频能播放吗？

是的，在对话里能播放。就是跟读训练时弹错。然后在同一个对话里，我再发一次同样的内容，就不会了。也是找不到规律。

**Comment by an-lee** [comment]
你有动过 /EnjoyLibrary 里的文件吗？

**Comment by JIM4ME** [comment]
没有

**Comment by an-lee** [comment]
应该已经修复
