### ISSUE TITLE
espeak-ng.data 找不到文件

### ISSUE THREAD

**Issue by allen2peace** [xiaolai/everyone-can-use-english#563]
你好，我这边调用 Echogarden.align 方法的时候，报错如下：

> Create alignment reference with eSpeak.. package error: [Error: ENOENT: no such file or directory, open '项目地址/.next/server/vendor-chunks/espeak-ng.data'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '项目地址/.next/server/vendor-chunks/espeak-ng.data'
}

请问这个是什么原因？

espeak-ng.data这个文件是从哪里生成的呢？需要放到哪个目录下？

**Comment by an-lee** [comment]
可能依赖安装失败了，`yarn install` 看看有没有报错信息？

eSpeak 是 echogarden 的依赖，还报错的话，可以参考 [echogarden](https://github.com/echogarden-project/echogarden) 项目检查一下看

**Comment by allen2peace** [comment]
感谢你的回答，实际上我在`echogarden`项目中也问了这个问题，根据作者的回复，我不是很肯定是哪里的问题导致的。

作者的回复在[这里](https://github.com/echogarden-project/echogarden/issues/48)

**Comment by an-lee** [comment]
哦，你是在自己的项目里跑 `Echogarden.align` 报错，不是在 Enjoy 项目里。

盲猜感觉问题可能出在打包上。
