### ISSUE TITLE
在调用echogarden库的ensureRawAudio方法的时候报错了，有人遇到相同的情况吗

### ISSUE THREAD

**Issue by shjames** [xiaolai/everyone-can-use-english#585]
![Snipaste_2024-05-02_13-36-30](https://github.com/xiaolai/everyone-can-use-english/assets/32636542/a00e7d7e-6de8-4a0d-b034-8621c173ac34)

**Comment by shjames** [comment]
附加一张报错信息：
![Snipaste_2024-05-02_14-32-21](https://github.com/xiaolai/everyone-can-use-english/assets/32636542/2fcd75a6-7640-4fa0-b69c-600b3f826604)

**Comment by an-lee** [comment]
应该是 `ffmpeg-static` 依赖没安装好，删掉 node_modules 重新 `yarn install` 试试。

参考 #570
