### ISSUE TITLE
主对话页面下，无法用快捷键（空格键）进行播放或暂停

### ISSUE THREAD

**Issue by JIM4ME** [xiaolai/everyone-can-use-english#606]
<img width="1436" alt="截屏2024-05-13 21 36 14" src="https://github.com/xiaolai/everyone-can-use-english/assets/56964139/6642b1ad-1773-487c-bf1c-8612b62e81af">

更新完v.0.2.5后，如题在这个页面下无法使用播放快捷键，上个版本没有这个问题。

**Comment by an-lee** [comment]
这个页面本来就没有适配快捷键。

**Comment by JIM4ME** [comment]
啊，难到原来的feature是个bug？之前的版本是可以的，感觉也很方便。希望可以加回来

**Comment by an-lee** [comment]
这个对话会有很多个音频，快捷键不能确保你要控制哪个音频，所以这里不会有快捷键控制。

**Comment by JIM4ME** [comment]
明白。因为我是一次训练就建一个对话，所以忽略了这个问题。估计之前是个bug，用着挺好：）
