### ISSUE TITLE
添加了音频以后，要怎么删除

### ISSUE THREAD

**Issue by jimmylgz** [xiaolai/everyone-can-use-english#616]
这边拿了一个测试的音频上传了，然后现在想下载，不敢在文件夹下直接删除文件，请问要怎么删除音频资源？

**Comment by an-lee** [comment]
没看明白你的意思。想下载就点下载，想删除就点删除。在音频资源页面，左上角可以切换到列表形式，能看到删除按钮

**Comment by jimmylgz** [comment]
> 没看明白你的意思。想下载就点下载，想删除就点删除。在音频资源页面，左上角可以切换到列表形式，能看到删除按钮

哦，没看到切换列表的选项，解决了，谢谢哈
