### ISSUE TITLE
OpenAI 配置的接口地址是否必须选三方中转服务（日常使用enjoy都是在有魔法情况下）

### ISSUE THREAD

**Issue by Yayamini** [xiaolai/everyone-can-use-english#660]
您好，

假如我在openai 官网采买 API key token 服务，并且日常使用enjoy是在有魔法情况下，还需要选第三方提供的中转服务吗？

**Comment by an-lee** [comment]
不需要。也可以不买 OpenAI 的 Key，直接使用 Enjoy 的服务，AI 引擎选用 EnjoyAI 就可以了。

**Comment by an-lee** [comment]
智能助手每个对话都可以独立设置 AI 引擎的。你报错的截图，右上角齿轮打开设置，应该选的是 OpenAI。你新建一个对话吧，确认 AI 引擎选的是 EnjoyAI 就可以用了。
