### ISSUE TITLE
无法录音

### ISSUE THREAD

**Issue by dongxudeng** [xiaolai/everyone-can-use-english#671]
点击enjoy的开始录音按钮后，使用耳机或外放无法进行录音。录音结束后提示：failedToSaveRecording:Error invoking remote method 'recordings-create':Error:未检测到任何声音。
使用的是win10系统（在设置-隐私-麦克风中，未能找到对enjoy的麦克风权限的修改）

**Comment by an-lee** [comment]
这个多半就是麦克风的设置问题，再检查一下看，比如麦克风的音量，是不是设置成了 0 之类的。
麦克风正常的话，录音时会有声波出现的

**Comment by dongxudeng** [comment]
好的，谢谢，问题已解决。
