### ISSUE TITLE
enjoyAPP的发音评估不能用，是怎么回事

### ISSUE THREAD

**Issue by Zhangjuanlli** [xiaolai/everyone-can-use-english#684]
![image](https://github.com/xiaolai/everyone-can-use-english/assets/68979481/2702a6ff-9fc0-44e9-9e2a-ab69c5322178)

**Comment by Zhangjuanlli** [comment]
明明下载安装更新到2.10版本，一用发现没有成功

**Comment by an-lee** [comment]
错误提示的意思是“余额不足“，充值后就可以了。发音评估是收费功能。

**Comment by Zhangjuanlli** [comment]
谢谢导演，哪些功能是收费的，我在哪里可以查看。3月充值了180 元

**Comment by an-lee** [comment]
> 谢谢导演，哪些功能是收费的，我在哪里可以查看。3月充值了180 元

https://1000h.org/enjoy 这里有文档
