### ISSUE TITLE
更新最新版本后报错

### ISSUE THREAD

**Issue by zhaoyl123** [xiaolai/everyone-can-use-english#695]
更新版本后报错SQLITE_ERROR: no such column: Audio language

**Comment by lyq760208** [comment]
<img width="960" alt="微信图片_20240620222805" src="https://github.com/xiaolai/everyone-can-use-english/assets/52565659/d6c6d8e3-c8f3-4a15-939e-e0d646e30dbc">

**Comment by an-lee** [comment]
稍等，马上发新版修复。

**Comment by an-lee** [comment]
更新到 v0.2.12 版本就正常了。
