### ISSUE TITLE
笑来老师的介绍的词典怎么安装

### ISSUE THREAD

**Issue by TomKing12** [xiaolai/everyone-can-use-english#70]
已经获得mdx和mdd文件。怎么打开呢？有教程吗

**Comment by samzwt** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件已收到。我最近正在休假或休息中，无法亲自回复您的邮件。

**Comment by gaoxiaopeng21** [comment]
https://zhuanlan.zhihu.com/p/630854573

**Comment by anyuzhe** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
