### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by LCSomeSSSS** [xiaolai/everyone-can-use-english#95]
有人遇到这两个错误吗

enjoy@workspace:enjoy doesn't provide vite (p50636), requested by vite-plugin-static-copy.
enjoy@workspace:enjoy doesn't provide vite (pe5759), requested by @vitejs/plugin-react.

<img width="805" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/19978628/f9c15931-2113-4d2d-914d-06844d6dd180">

**Comment by YangZhengCQ** [comment]
进入 'everyone-can-use-english/enjoy' 目录再执行 yarn Install 就没问题了。

**Comment by YanJun1024** [comment]
![enjoy_error](https://github.com/xiaolai/everyone-can-use-english/assets/73935988/214b8f14-b501-410b-8499-e24e695cc4d5)
我这儿也有些错误，希望懂得朋友支招[抱拳]

**Comment by AkaShark** [comment]
similar problem

**Comment by DukeDeng** [comment]
similar problem

**Comment by GGGkkq** [comment]
我也是这样的
![image](https://github.com/xiaolai/everyone-can-use-english/assets/113406399/b1247f1b-7d1d-4b05-847b-b957bc6be1de)

**Comment by yongbowa** [comment]
> 我也是这样的 ![image](https://private-user-images.githubusercontent.com/113406399/297286618-b1247f1b-7d1d-4b05-847b-b957bc6be1de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDg5NzQsIm5iZiI6MTcwNTc0ODY3NCwicGF0aCI6Ii8xMTM0MDYzOTkvMjk3Mjg2NjE4LWIxMjQ3ZjFiLTdkMWQtNGIwNS04NDdiLWI5NTdiYzZiZTFkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxMTA0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Zjc0NDk3Yzk3NTFiNjJhNWU3ZjFkZTFlN2NkNWYyOTkzMGQxZDJjOTBkZWVjMGJiNDAyYzgyMDUyMGNmMjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xv_J5ahFxvrBaJJwDqtdJlxdpSBqBE0Yd4fWfKypzh8)

我碰到了同样的报错，请查看提示的log 路径下对应的log文件，你这里的路径是C:\Users\user\AppData\Local\Temp\xfs-c7ccba4\build.log
我的问题有：
1.没有安装Visual studio 软件
2.安装后再次run，报的是没有VC++ toolset，在Visual studio安装的时候可以选
3.解决上述两个问题后还存在windows SDK missing的问题，同样可以在Visual studio 安装的时候选择
![image](https://github.com/xiaolai/everyone-can-use-english/assets/56637457/0f75e77b-3b9f-49ba-81d6-cb8196a21226)
