### ISSUE TITLE
“英语教练” 功能是可用的么？

### ISSUE THREAD

**Issue by pierrelzw** [xiaolai/everyone-can-use-english#97]
我使用 yarn install 方式安装的软件
更新了 openai-key
创建英语教练机器人以后，发送了文字，但是一直在转⭕️，没有结果返回
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/eb321e24-9102-4e61-85c2-f79d2a2a7156)
看了一下命令行窗口的提示，错误如下
> 2024-01-13 11:50:12.255 Electron Helper (Renderer)[45668:1846446] CoreText note: Client requested name ".PingFangSC-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-01-13 11:50:12.286 Electron Helper (Renderer)[45668:1846446] CoreText note: Client requested name ".PingFangSC-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
[llm/error] [1:chain:ConversationChain > 2:llm:ChatOpenAI] [175.38s] LLM run errored with error: "Connection error."
[chain/error] [1:chain:ConversationChain] [175.38s] Chain run errored with error: "Connection error."
2024-01-13 12:08:04.738 Electron Helper (Renderer)[45668:1846446] CoreText note: Client requested name ".PingFangSC-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

**Comment by lgqbee** [comment]
可用的，必须有openai api key。在“我的”——“软件设置”——“基本设置”里，输入Openai key后，保存，就能用了。
![2](https://github.com/xiaolai/everyone-can-use-english/assets/57405578/038f95f9-2322-4303-a072-b3b3752ec69b)

![1](https://github.com/xiaolai/everyone-can-use-english/assets/57405578/edbfede2-a102-43e2-bdf8-7a130e7db0a1)

**Comment by pierrelzw** [comment]
> 可用的，必须有openai api key。在“我的”——“软件设置”——“基本设置”里，输入Openai key后，保存，就能用了。 ![2](https://private-user-images.githubusercontent.com/57405578/296413636-038f95f9-2322-4303-a072-b3b3752ec69b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTc0NTYsIm5iZiI6MTcwNTExNzE1NiwicGF0aCI6Ii81NzQwNTU3OC8yOTY0MTM2MzYtMDM4Zjk1ZjktMjMyMi00MzAzLWEwNzItYjNiMzc1MmVjNjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDAzMzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhY2JkOTlkOWE2MmFiOTJiNWY0NDExZWIyOTVmMzE3ZTFlOWQ1MmYxYmZiMjVkZGI0N2M4ZWQ5ZWViMjA4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sWWCbTQ2kgf4QoWYtiklXupt9gy95gcXryFnaUKuGuY)
> 
> ![1](https://private-user-images.githubusercontent.com/57405578/296413647-edbfede2-a102-43e2-bdf8-7a130e7db0a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTc0NTYsIm5iZiI6MTcwNTExNzE1NiwicGF0aCI6Ii81NzQwNTU3OC8yOTY0MTM2NDctZWRiZmVkZTItYTEwMi00M2UyLWJkZjgtN2ExMzBlN2RiMGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDAzMzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjNkYmM4MmQ3MDg5OTJjOGFiODI3MzhiMGIxODVlMjJiNDJjZDIwMGU2YTI4ZTg5NzA3OWY5Y2JhNWJhMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h8sALNYsqzjvMUMmnwa1-86KEBmqKRWFRtO3q9G9YNM)

感谢，我配置了 openai-key，不过还是不行，可能是我的网络原因，我再试试

**Comment by jarodlong7788** [comment]
同样的问题，访问openai可以，填写了api一直连接不上。

**Comment by chongziyeshirou** [comment]
我是出现401无效的令牌报错，一直连接不上。

**Comment by chongziyeshirou** [comment]
> 可用的，必须有openai api key。在“我的”——“软件设置”——“基本设置”里，输入Openai key后，保存，就能用了。 ![2](https://private-user-images.githubusercontent.com/57405578/296413636-038f95f9-2322-4303-a072-b3b3752ec69b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTUwOTksIm5iZiI6MTcwNTQxNDc5OSwicGF0aCI6Ii81NzQwNTU3OC8yOTY0MTM2MzYtMDM4Zjk1ZjktMjMyMi00MzAzLWEwNzItYjNiMzc1MmVjNjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE0MTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWViMDY5Mzc0MjZkNmQ4ZGNmN2JhMTJiZjY4ZWYzN2JiN2E2NjEzYTgzNjBiODRiNjBhYjA3ZjMyYjM0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XqhVbAJU8ZF2rQ-Pb0U5mrOpohwo4nN8bHkUKDgrVU4)
> 
> ![1](https://private-user-images.githubusercontent.com/57405578/296413647-edbfede2-a102-43e2-bdf8-7a130e7db0a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTUwOTksIm5iZiI6MTcwNTQxNDc5OSwicGF0aCI6Ii81NzQwNTU3OC8yOTY0MTM2NDctZWRiZmVkZTItYTEwMi00M2UyLWJkZjgtN2ExMzBlN2RiMGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE0MTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZGNkNTJmOWUyNzJmMzY4NWE0NzU5ZTZkY2E0ZGQzM2M0YjZjMjEwYjQ4MGE4ZGY0YTg2ZDI5Yjg4YjQzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxYpMggbiKIQ9P5qzvuZBbvKikFichBvNaR1Hm0GzhI)

请问OpenAI的key使用的是3.5还是4.0版本的？

**Comment by dayangshanbaoye** [comment]
我也是遇到类似的问题，即便更换了很多个api key，发送完中文后就一直转圈圈

**Comment by lgqbee** [comment]
我是用的买的中转key，在设置里保存OpenAI api key后，还需要在智能对话的，“请求地址”和“TTS地址”填上，“https://oneapi.xty.app/v1”，就能联通使用。不知道大家若是使用的直连key是否也需要配置一些东西，才能联通。

**Comment by Barryonion** [comment]
<img width="590" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/36102327/c842ef8c-0b36-4feb-91c4-d2500288d320">
遇到了这个报错
系统：<img width="201" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/36102327/200876e5-8d74-49e4-9cc5-0e836c51e6c2">
会话配置：
<img width="377" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/36102327/0e1c88b3-2352-42bc-a586-c0f1c62856bd">
用其他软件验证apikey是可用的
<img width="538" alt="image" src="https://github.com/xiaolai/everyone-can-use-english/assets/36102327/3165ec46-d967-4c48-bf86-c8fd227335d2">

**Comment by chongziyeshirou** [comment]
> 我是用的买的中转key，在设置里保存OpenAI api key后，还需要在智能对话的，“请求地址”和“TTS地址”填上，“[https://oneapi.xty.app/v1”。](https://oneapi.xty.app/v1%E2%80%9D%E3%80%82) 就能联通使用。不知道大家若是使用的直连key是否也需要配置一些东西，才能联通。

中转KEY才行   我已经可以了

**Comment by jarodlong7788** [comment]
这个中转应该怎么做

**Comment by an-lee** [comment]
https://1000h.org/enjoy-app/
