### ISSUE TITLE
内联字幕功能如何使用？

### ISSUE THREAD

**Issue by pierrelzw** [xiaolai/everyone-can-use-english#98]
是需要某种特定格式的字幕文件么？目前只能看听语音播放，看不到文字。
我注意到有语音转文本，以及内联字幕功能，不过目前看起来还不能使用？
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/bb15b4e7-3fbd-41d3-b5cb-a635b39f16ad)

![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/8a87a6fd-b1b7-4bb5-81bb-31a30795d1a7)

**Comment by an-lee** [comment]
应该是 ffmpeg 没安装成功，语音转文本没有成功。

用的是 Mac 什么芯片的？

**Comment by pierrelzw** [comment]
> 应该是 ffmpeg 没安装成功，语音转文本没有成功。
> 
> 用的是 Mac 什么芯片的？

Intel，macOS，Big Sur, 看起来 ffmpeg 是有的。我尝试用它把几张图片转为视频，也是成功的
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/8e0a10d9-c75c-40c4-9957-6e7665c75a76)
![image](https://github.com/xiaolai/everyone-can-use-english/assets/13348529/95e943fc-afd5-497c-a2de-1f9ead24f81c)

**Comment by an-lee** [comment]
Macos 11 可能无法使用本地的 whisper 服务，新版本支持了其他 STT 服务选项，可以试试。
